# If your theme is not using the supported directory structure, provide the root path
# where to find the `templates/`, `sections/`, `snippets/` directories as they would
# be uploaded to Shopify.
root: Curalife-Theme-Build

# Use default settings for all checks
TemplateLength:
  enabled: true

VariableName:
  enabled: true

SchemaJsonFormat:
  enabled: true

ValidSchema:
  enabled: true

ValidJson:
  enabled: true

# Add debug mode
debug: true
