name: "Setup Environment"
description: "Sets up Node.js and installs system dependencies"

inputs:
  cache-key-prefix:
    description: "Prefix for the system dependencies cache key"
    required: true
  npm-cache-key:
    description: "Cache key for npm global packages"
    required: true
  puppeteer-cache-key:
    description: "Cache key for Puppeteer"
    required: false
  tools-cache-key:
    description: "Cache key for tools"
    required: false

runs:
  using: "composite"
  steps:
    # Setup Node.js first
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    # Ensure cache directories exist
    - name: Create cache directories
      shell: bash
      run: |
        mkdir -p /home/runner/.cache/apt
        mkdir -p /home/runner/.apt-cache
        mkdir -p /home/runner/.cache/tools
        mkdir -p /home/runner/.cache/puppeteer
        mkdir -p /home/runner/.cache/logs
        mkdir -p /home/runner/.npm

    # Consolidated cache for all tools and dependencies
    - name: Cache all dependencies
      uses: actions/cache@v4
      id: cache-all-deps
      with:
        path: |
          /home/runner/.cache/apt
          /home/runner/.apt-cache
          /home/runner/.cache/tools
          /home/runner/.cache/puppeteer
          /home/runner/.npm
        key: ${{ inputs.cache-key-prefix }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}

    - name: Cache log and report
      shell: bash
      run: |
        echo "Cache hit status: ${{ steps.cache-all-deps.outputs.cache-hit }}"
        if [ "${{ steps.cache-all-deps.outputs.cache-hit }}" == "true" ]; then
          echo "Using cached dependencies from key: ${{ inputs.cache-key-prefix }}" > /home/runner/.cache/logs/cache-status.log
          echo "Cache hit timestamp: $(date)" >> /home/runner/.cache/logs/cache-status.log
        else
          echo "Cache miss for key: ${{ inputs.cache-key-prefix }}" > /home/runner/.cache/logs/cache-status.log
          echo "Building new cache at: $(date)" >> /home/runner/.cache/logs/cache-status.log
        fi

    - name: Install tools and dependencies
      shell: bash
      run: |
        echo "Installing system dependencies and tools..."

        # Install apt packages conditionally
        if [ "${{ steps.cache-all-deps.outputs.cache-hit }}" != "true" ]; then
          echo "Cache miss - installing apt packages from scratch"
          sudo apt-get update && sudo apt-get install -y jq bc
        else
          echo "Cache hit - using cached apt packages when possible"
          sudo apt-get install -y jq bc --no-update
        fi

        echo "Installing global npm packages..."
        # Only install if not already installed or cache miss
        if [ "${{ steps.cache-all-deps.outputs.cache-hit }}" != "true" ] || ! command -v lighthouse &> /dev/null; then
          npm config set cache /home/runner/.npm --global
          npm install -g @lhci/cli lighthouse puppeteer-screenshot-cli
        else
          echo "Using cached npm global packages"
        fi

    # Direct approach to install Puppeteer with Chromium
    - name: Install Puppeteer with Chromium
      shell: bash
      run: |
        echo "Installing Puppeteer with Chromium directly..."

        # Set environment variables to ensure Chromium is downloaded
        export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
        export PUPPETEER_DOWNLOAD_PATH=/home/runner/.cache/puppeteer

        # Install Puppeteer globally with Chromium
        npm install -g puppeteer@19.11.1

        # Additional direct installation of Chrome binary to ensure it's available
        mkdir -p /home/runner/.cache/puppeteer
        cd /home/runner/.cache/puppeteer

        echo "Downloading and verifying Chrome binary..."
        # Install Chromium directly using puppeteer CLI
        npx --yes puppeteer browsers install chrome

        # Mark as successfully installed
        touch /home/runner/.cache/puppeteer/installed

        # Verify Chrome is available
        chrome_path=$(node -e "console.log(require('puppeteer').executablePath())")
        echo "Chrome executable path: $chrome_path"

        if [ -f "$chrome_path" ]; then
          echo "Chrome binary verified at: $chrome_path"
        else
          echo "Chrome binary not found at expected path: $chrome_path"
          exit 1
        fi

        # Test that puppeteer works
        echo "Testing Puppeteer with actual browser launch..."
        node -e "
        const puppeteer = require('puppeteer');
        async function test() {
          console.log('Launching browser...');
          const browser = await puppeteer.launch({
            headless: 'new',
            args: ['--no-sandbox', '--disable-dev-shm-usage']
          });
          console.log('Browser launched successfully');
          const page = await browser.newPage();
          console.log('Page created');
          await browser.close();
          console.log('Test successful');
        }
        test().catch(e => {
          console.error('Puppeteer test failed:', e);
          process.exit(1);
        });"

    - name: Set Chrome flags
      shell: bash
      run: |
        echo "CHROME_FLAGS=--no-sandbox --disable-dev-shm-usage --disable-gpu --headless --disable-extensions" >> $GITHUB_ENV
        echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false" >> $GITHUB_ENV
        echo "PUPPETEER_DOWNLOAD_PATH=/home/runner/.cache/puppeteer" >> $GITHUB_ENV
