name: "Setup Environment"
description: "Sets up Node.js and installs all dependencies needed for Lighthouse CI"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "18"
  cache-dependencies:
    description: "Whether to cache dependencies"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    # Setup Node with built-in caching
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    # Install system dependencies with caching
    - name: Cache system dependencies
      id: cache-sys-deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/apt
          ~/.apt-cache
        key: ${{ runner.os }}-apt-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    # Install jq and bc (for data processing)
    - name: Install system tools
      shell: bash
      run: |
        echo "Installing system tools..."
        # Create cache directories if needed
        mkdir -p ~/.cache/apt ~/.apt-cache

        # Install required tools
        sudo apt-get update && sudo apt-get install -y jq bc

    # Install Puppeteer with Chrome
    - name: Cache Puppeteer & Chrome
      id: cache-puppeteer
      if: inputs.cache-dependencies == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.cache/puppeteer
        key: ${{ runner.os }}-puppeteer-${{ hashFiles('**/package.json') }}

    # Create Puppeteer cache directory
    - name: Setup Puppeteer
      shell: bash
      run: |
        echo "Setting up Puppeteer..."
        mkdir -p ~/.cache/puppeteer
        echo "PUPPETEER_CACHE_DIR=~/.cache/puppeteer" >> $GITHUB_ENV
        echo "CHROME_FLAGS=--no-sandbox --disable-dev-shm-usage --disable-gpu --headless" >> $GITHUB_ENV

    # Install global dependencies
    - name: Install global dependencies
      shell: bash
      run: |
        echo "Installing global dependencies..."
        npm install -g @lhci/cli lighthouse puppeteer-core

    # Check for package.json and install local dependencies if available
    - name: Install local dependencies
      shell: bash
      run: |
        if [ -f "package.json" ]; then
          if [ -f "package-lock.json" ]; then
            echo "Installing dependencies with npm ci..."
            npm ci
          else
            echo "Installing dependencies with npm install..."
            npm install
          fi
        else
          echo "No package.json found. Creating minimal package.json for Lighthouse dependencies..."
          mkdir -p .github/workflows/templates
          if [ -f ".github/workflows/templates/lighthouse-package.json.template" ]; then
            cat ".github/workflows/templates/lighthouse-package.json.template" > package.json
            npm install
          else
            echo '{"name":"lighthouse-ci-minimal","version":"1.0.0","dependencies":{"@lhci/cli":"^0.12.0"}}' > package.json
            npm install
          fi
        fi

    # Verify installation
    - name: Verify installation
      shell: bash
      run: |
        echo "Verifying installation..."
        node --version
        npm --version
        npx lighthouse --version || echo "Lighthouse not installed correctly"
        npx lhci --version || echo "LHCI not installed correctly"
