#!/bin/bash

# This script generates the main performance dashboard HTML file
# Usage: ./generate-dashboard.sh [CURRENT_DATE]

# Get parameters
CURRENT_DATE=$1

# Exit if required parameters are missing
if [ -z "$CURRENT_DATE" ]; then
  echo "Error: Missing required parameters"
  echo "Usage: ./generate-dashboard.sh [CURRENT_DATE]"
  exit 1
fi

# Create the main index.html file
INDEX_HTML="performance-reports/index.html"
echo "Creating index HTML file at $INDEX_HTML"

# Create HTML header and start of body
echo "<!DOCTYPE html>" > "$INDEX_HTML"
echo "<html lang=\"en\">" >> "$INDEX_HTML"
echo "<head>" >> "$INDEX_HTML"
echo "  <meta charset=\"UTF-8\">" >> "$INDEX_HTML"
echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> "$INDEX_HTML"
echo "  <title>Lighthouse Performance Dashboard | Curalife</title>" >> "$INDEX_HTML"
echo "  <link rel=\"icon\" href=\"https://cdn.shopify.com/s/files/1/0016/8633/0243/files/favicon-32x32.png?v=1618828796\" type=\"image/png\">" >> "$INDEX_HTML"
echo "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">" >> "$INDEX_HTML"
echo "  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\">" >> "$INDEX_HTML"
echo "  <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>" >> "$INDEX_HTML"
echo "  <style>" >> "$INDEX_HTML"
echo "    :root {" >> "$INDEX_HTML"
echo "      --primary-color: #00837b;" >> "$INDEX_HTML"
echo "      --primary-light: #e6f7f5;" >> "$INDEX_HTML"
echo "      --secondary-color: #f26b3c;" >> "$INDEX_HTML"
echo "      --dark-color: #2c3e50;" >> "$INDEX_HTML"
echo "      --good: #0CCE6B;" >> "$INDEX_HTML"
echo "      --average: #FFA400;" >> "$INDEX_HTML"
echo "      --poor: #FF4E42;" >> "$INDEX_HTML"
echo "      --background: #f8f9fa;" >> "$INDEX_HTML"
echo "      --card-bg: #ffffff;" >> "$INDEX_HTML"
echo "      --text-color: #333333;" >> "$INDEX_HTML"
echo "      --border-radius: 10px;" >> "$INDEX_HTML"
echo "      --shadow: 0 4px 12px rgba(0,0,0,0.1);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    body {" >> "$INDEX_HTML"
echo "      font-family: 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;" >> "$INDEX_HTML"
echo "      line-height: 1.6;" >> "$INDEX_HTML"
echo "      max-width: 1400px;" >> "$INDEX_HTML"
echo "      margin: 0 auto;" >> "$INDEX_HTML"
echo "      padding: 20px;" >> "$INDEX_HTML"
echo "      background-color: var(--background);" >> "$INDEX_HTML"
echo "      color: var(--text-color);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .dashboard-header {" >> "$INDEX_HTML"
echo "      background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));" >> "$INDEX_HTML"
echo "      color: white;" >> "$INDEX_HTML"
echo "      padding: 2rem;" >> "$INDEX_HTML"
echo "      border-radius: var(--border-radius);" >> "$INDEX_HTML"
echo "      margin-bottom: 2rem;" >> "$INDEX_HTML"
echo "      box-shadow: var(--shadow);" >> "$INDEX_HTML"
echo "      display: flex;" >> "$INDEX_HTML"
echo "      justify-content: space-between;" >> "$INDEX_HTML"
echo "      align-items: center;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    h1, h2, h3 { color: var(--dark-color); margin-top: 1.5rem; }" >> "$INDEX_HTML"
echo "    .card {" >> "$INDEX_HTML"
echo "      background: var(--card-bg);" >> "$INDEX_HTML"
echo "      border-radius: var(--border-radius);" >> "$INDEX_HTML"
echo "      padding: 20px;" >> "$INDEX_HTML"
echo "      margin-bottom: 20px;" >> "$INDEX_HTML"
echo "      box-shadow: var(--shadow);" >> "$INDEX_HTML"
echo "      transition: transform 0.3s, box-shadow 0.3s;" >> "$INDEX_HTML"
echo "      border: none;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .card:hover {" >> "$INDEX_HTML"
echo "      transform: translateY(-5px);" >> "$INDEX_HTML"
echo "      box-shadow: 0 10px 20px rgba(0,0,0,0.1);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .card-header {" >> "$INDEX_HTML"
echo "      background-color: rgba(0,0,0,0.03);" >> "$INDEX_HTML"
echo "      border-bottom: none;" >> "$INDEX_HTML"
echo "      font-weight: 600;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .target-line {" >> "$INDEX_HTML"
echo "      background-color: rgba(234, 67, 53, 0.1);" >> "$INDEX_HTML"
echo "      padding: 0.5rem;" >> "$INDEX_HTML"
echo "      border-radius: 5px;" >> "$INDEX_HTML"
echo "      margin-bottom: 1rem;" >> "$INDEX_HTML"
echo "      text-align: center;" >> "$INDEX_HTML"
echo "      font-weight: 500;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .metric-card {" >> "$INDEX_HTML"
echo "      text-align: center;" >> "$INDEX_HTML"
echo "      padding: 1.5rem;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .metric-value {" >> "$INDEX_HTML"
echo "      font-size: 2.5rem;" >> "$INDEX_HTML"
echo "      font-weight: bold;" >> "$INDEX_HTML"
echo "      margin-bottom: 5px;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .metric-label {" >> "$INDEX_HTML"
echo "      font-size: 0.9rem;" >> "$INDEX_HTML"
echo "      color: #6c757d;" >> "$INDEX_HTML"
echo "      text-transform: uppercase;" >> "$INDEX_HTML"
echo "      letter-spacing: 1px;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .pill {" >> "$INDEX_HTML"
echo "      display: inline-block;" >> "$INDEX_HTML"
echo "      padding: 0.25rem 0.75rem;" >> "$INDEX_HTML"
echo "      border-radius: 50px;" >> "$INDEX_HTML"
echo "      font-size: 0.8rem;" >> "$INDEX_HTML"
echo "      font-weight: 500;" >> "$INDEX_HTML"
echo "      margin-right: 5px;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .good {" >> "$INDEX_HTML"
echo "      background-color: rgba(12, 206, 107, 0.2);" >> "$INDEX_HTML"
echo "      color: var(--good);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .average {" >> "$INDEX_HTML"
echo "      background-color: rgba(255, 164, 0, 0.2);" >> "$INDEX_HTML"
echo "      color: var(--average);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .poor {" >> "$INDEX_HTML"
echo "      background-color: rgba(255, 78, 66, 0.2);" >> "$INDEX_HTML"
echo "      color: var(--poor);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .chart-container {" >> "$INDEX_HTML"
echo "      position: relative;" >> "$INDEX_HTML"
echo "      height: 300px;" >> "$INDEX_HTML"
echo "      margin-bottom: 2rem;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .table {" >> "$INDEX_HTML"
echo "      margin-top: 1.5rem;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .table th {" >> "$INDEX_HTML"
echo "      background-color: #f8f9fa;" >> "$INDEX_HTML"
echo "      font-weight: 600;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .badge-score {" >> "$INDEX_HTML"
echo "      font-size: 1rem;" >> "$INDEX_HTML"
echo "      padding: 0.3rem 0.6rem;" >> "$INDEX_HTML"
echo "      border-radius: 50px;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .badge-90plus {" >> "$INDEX_HTML"
echo "      background-color: var(--good);" >> "$INDEX_HTML"
echo "      color: white;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .badge-75to89 {" >> "$INDEX_HTML"
echo "      background-color: var(--average);" >> "$INDEX_HTML"
echo "      color: #212529;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .badge-below75 {" >> "$INDEX_HTML"
echo "      background-color: var(--poor);" >> "$INDEX_HTML"
echo "      color: white;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .recommendation {" >> "$INDEX_HTML"
echo "      padding: 1.2rem;" >> "$INDEX_HTML"
echo "      margin-bottom: 1.2rem;" >> "$INDEX_HTML"
echo "      border-left: 4px solid var(--primary-color);" >> "$INDEX_HTML"
echo "      background-color: var(--primary-light);" >> "$INDEX_HTML"
echo "      border-radius: 6px;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .recommendation h4 {" >> "$INDEX_HTML"
echo "      color: var(--primary-color);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .btn-detail, .btn-primary {" >> "$INDEX_HTML"
echo "      background-color: var(--primary-color);" >> "$INDEX_HTML"
echo "      color: white;" >> "$INDEX_HTML"
echo "      border: none;" >> "$INDEX_HTML"
echo "      padding: 0.5rem 1.2rem;" >> "$INDEX_HTML"
echo "      border-radius: 4px;" >> "$INDEX_HTML"
echo "      text-decoration: none;" >> "$INDEX_HTML"
echo "      display: inline-block;" >> "$INDEX_HTML"
echo "      transition: background-color 0.2s;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .btn-detail:hover, .btn-primary:hover {" >> "$INDEX_HTML"
echo "      background-color: #006d66;" >> "$INDEX_HTML"
echo "      color: white;" >> "$INDEX_HTML"
echo "      text-decoration: none;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .btn-secondary {" >> "$INDEX_HTML"
echo "      background-color: var(--secondary-color);" >> "$INDEX_HTML"
echo "      color: white;" >> "$INDEX_HTML"
echo "      border: none;" >> "$INDEX_HTML"
echo "      padding: 0.5rem 1.2rem;" >> "$INDEX_HTML"
echo "      border-radius: 4px;" >> "$INDEX_HTML"
echo "      text-decoration: none;" >> "$INDEX_HTML"
echo "      display: inline-block;" >> "$INDEX_HTML"
echo "      transition: background-color 0.2s;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .btn-secondary:hover {" >> "$INDEX_HTML"
echo "      background-color: #e05a2d;" >> "$INDEX_HTML"
echo "      color: white;" >> "$INDEX_HTML"
echo "      text-decoration: none;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .metrics-grid {" >> "$INDEX_HTML"
echo "      display: grid;" >> "$INDEX_HTML"
echo "      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));" >> "$INDEX_HTML"
echo "      gap: 20px;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .metric-title {" >> "$INDEX_HTML"
echo "      font-size: 1rem;" >> "$INDEX_HTML"
echo "      font-weight: 600;" >> "$INDEX_HTML"
echo "      color: var(--dark-color);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .metric-visual {" >> "$INDEX_HTML"
echo "      display: flex;" >> "$INDEX_HTML"
echo "      align-items: center;" >> "$INDEX_HTML"
echo "      justify-content: center;" >> "$INDEX_HTML"
echo "      margin: 10px 0;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .metric-visual .value {" >> "$INDEX_HTML"
echo "      font-size: 2rem;" >> "$INDEX_HTML"
echo "      font-weight: bold;" >> "$INDEX_HTML"
echo "      margin-right: 10px;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .metric-description {" >> "$INDEX_HTML"
echo "      font-size: 0.85rem;" >> "$INDEX_HTML"
echo "      color: #6c757d;" >> "$INDEX_HTML"
echo "      margin-top: 10px;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .action-needed {" >> "$INDEX_HTML"
echo "      background-color: rgba(255, 78, 66, 0.1);" >> "$INDEX_HTML"
echo "      border-left: 4px solid var(--poor);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .opportunity {" >> "$INDEX_HTML"
echo "      background-color: rgba(255, 164, 0, 0.1);" >> "$INDEX_HTML"
echo "      border-left: 4px solid var(--average);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .passed {" >> "$INDEX_HTML"
echo "      background-color: rgba(12, 206, 107, 0.1);" >> "$INDEX_HTML"
echo "      border-left: 4px solid var(--good);" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .section-title {" >> "$INDEX_HTML"
echo "      font-weight: 600;" >> "$INDEX_HTML"
echo "      color: var(--dark-color);" >> "$INDEX_HTML"
echo "      margin-bottom: 15px;" >> "$INDEX_HTML"
echo "      border-bottom: 2px solid var(--primary-light);" >> "$INDEX_HTML"
echo "      padding-bottom: 10px;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    .nav-actions {" >> "$INDEX_HTML"
echo "      display: flex;" >> "$INDEX_HTML"
echo "      gap: 10px;" >> "$INDEX_HTML"
echo "      align-items: center;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    @media (max-width: 768px) {" >> "$INDEX_HTML"
echo "      .metrics-grid {" >> "$INDEX_HTML"
echo "        grid-template-columns: 1fr;" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "      .dashboard-header {" >> "$INDEX_HTML"
echo "        flex-direction: column;" >> "$INDEX_HTML"
echo "        text-align: center;" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "      .nav-actions {" >> "$INDEX_HTML"
echo "        margin-top: 15px;" >> "$INDEX_HTML"
echo "        justify-content: center;" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "    footer, .footer {" >> "$INDEX_HTML"
echo "      margin-top: 3rem;" >> "$INDEX_HTML"
echo "      padding-top: 1.5rem;" >> "$INDEX_HTML"
echo "      border-top: 1px solid #dee2e6;" >> "$INDEX_HTML"
echo "      color: #6c757d;" >> "$INDEX_HTML"
echo "      text-align: center;" >> "$INDEX_HTML"
echo "      font-size: 0.9rem;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"
echo "  </style>" >> "$INDEX_HTML"
echo "</head>" >> "$INDEX_HTML"
echo "<body>" >> "$INDEX_HTML"

# Add header section
echo "  <div class=\"dashboard-header\">" >> "$INDEX_HTML"
echo "    <div class=\"d-flex align-items-center\">" >> "$INDEX_HTML"
echo "      <i class=\"bi bi-speedometer2 fs-1 me-3\"></i>" >> "$INDEX_HTML"
echo "      <div>" >> "$INDEX_HTML"
echo "        <h1 class=\"mb-0\">Lighthouse Performance Dashboard</h1>" >> "$INDEX_HTML"
echo "        <p class=\"mb-0 mt-2\">Tracking website performance metrics from automated Lighthouse tests.</p>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"
echo "    </div>" >> "$INDEX_HTML"
echo "    <div>" >> "$INDEX_HTML"
echo "      <p class=\"mb-0\">Last updated: $CURRENT_DATE</p>" >> "$INDEX_HTML"
echo "      <div class=\"nav-actions mt-2\">" >> "$INDEX_HTML"
echo "        <a href=\"trends.html\" class=\"btn-secondary\"><i class=\"bi bi-graph-up-arrow me-2\"></i>View Trends</a>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"
echo "    </div>" >> "$INDEX_HTML"
echo "  </div>" >> "$INDEX_HTML"

# Add container for content
echo "  <div class=\"container-fluid p-0\">" >> "$INDEX_HTML"
echo "    <div class=\"row\">" >> "$INDEX_HTML"

# Add status card
echo "      <div class=\"col-md-12 mb-4\">" >> "$INDEX_HTML"
echo "        <div class=\"card\">" >> "$INDEX_HTML"
echo "          <div class=\"card-header\">" >> "$INDEX_HTML"
echo "            <h5 class=\"mb-0\">Dashboard Status</h5>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "          <div class=\"card-body\">" >> "$INDEX_HTML"
echo "            <div class=\"alert alert-info\">" >> "$INDEX_HTML"
echo "              <i class=\"bi bi-info-circle-fill me-2\"></i> This dashboard provides insights into the performance of Curalife's website based on Google's Core Web Vitals and other key metrics. Tests are run twice daily with mobile and desktop devices." >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

# Add metrics overview section
echo "      <div class=\"col-md-12 mb-4\">" >> "$INDEX_HTML"
echo "        <div class=\"card\">" >> "$INDEX_HTML"
echo "          <div class=\"card-header d-flex justify-content-between align-items-center\">" >> "$INDEX_HTML"
echo "            <h5 class=\"mb-0\"><i class=\"bi bi-lightning-charge me-2\"></i>Performance Overview</h5>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "          <div class=\"card-body\">" >> "$INDEX_HTML"
echo "            <div class=\"row\">" >> "$INDEX_HTML"

# Add average score metrics
echo "              <div class=\"col-md-3\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                  <div class=\"metric-value\" id=\"avg-perf\">Calculating...</div>" >> "$INDEX_HTML"
echo "                  <div class=\"metric-label\">Average Performance Score</div>" >> "$INDEX_HTML"
echo "                  <div class=\"mt-3\"><small class=\"text-muted\">Target: 90+</small></div>" >> "$INDEX_HTML"
echo "                </div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"

echo "              <div class=\"col-md-3\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                  <div class=\"metric-value\" id=\"avg-a11y\">Calculating...</div>" >> "$INDEX_HTML"
echo "                  <div class=\"metric-label\">Average Accessibility Score</div>" >> "$INDEX_HTML"
echo "                  <div class=\"mt-3\"><small class=\"text-muted\">Target: 90+</small></div>" >> "$INDEX_HTML"
echo "                </div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"

echo "              <div class=\"col-md-3\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                  <div class=\"metric-value\" id=\"avg-bp\">Calculating...</div>" >> "$INDEX_HTML"
echo "                  <div class=\"metric-label\">Average Best Practices</div>" >> "$INDEX_HTML"
echo "                  <div class=\"mt-3\"><small class=\"text-muted\">Target: 90+</small></div>" >> "$INDEX_HTML"
echo "                </div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"

echo "              <div class=\"col-md-3\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                  <div class=\"metric-value\" id=\"avg-seo\">Calculating...</div>" >> "$INDEX_HTML"
echo "                  <div class=\"metric-label\">Average SEO Score</div>" >> "$INDEX_HTML"
echo "                  <div class=\"mt-3\"><small class=\"text-muted\">Target: 90+</small></div>" >> "$INDEX_HTML"
echo "                </div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

# Add Core Web Vitals section with additional explanation
echo "      <div class=\"col-md-12 mb-4\">" >> "$INDEX_HTML"
echo "        <div class=\"card\">" >> "$INDEX_HTML"
echo "          <div class=\"card-header\">" >> "$INDEX_HTML"
echo "            <h5 class=\"mb-0\"><i class=\"bi bi-heart-pulse me-2\"></i>Core Web Vitals</h5>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "          <div class=\"card-body\">" >> "$INDEX_HTML"
echo "            <p>Core Web Vitals are a set of specific factors that Google considers important in a webpage's overall user experience. They are part of Google's Page Experience signals used to measure user experience and affect search engine rankings.</p>" >> "$INDEX_HTML"
echo "            <div class=\"target-line mb-3\">Target: LCP < 2.5s | CLS < 0.1 | FID < 100ms</div>" >> "$INDEX_HTML"
echo "            <div class=\"row\">" >> "$INDEX_HTML"

echo "              <div class=\"col-md-4\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                  <div class=\"metric-title\">Largest Contentful Paint (LCP)</div>" >> "$INDEX_HTML"
echo "                  <div class=\"metric-value\" id=\"avg-lcp\">Calculating...</div>" >> "$INDEX_HTML"
echo "                  <div class=\"mt-2\"><small class=\"text-muted\">Good: < 2.5s | Needs Improvement: 2.5s - 4s | Poor: > 4s</small></div>" >> "$INDEX_HTML"
echo "                  <div class=\"mt-3\"><small>Measures loading performance. To provide a good user experience, LCP should occur within 2.5 seconds of when the page first starts loading.</small></div>" >> "$INDEX_HTML"
echo "                </div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"

echo "              <div class=\"col-md-4\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                  <div class=\"metric-title\">First Input Delay (FID)</div>" >> "$INDEX_HTML"
echo "                  <div class=\"metric-value\" id=\"avg-fid\">Calculating...</div>" >> "$INDEX_HTML"
echo "                  <div class=\"mt-2\"><small class=\"text-muted\">Good: < 100ms | Needs Improvement: 100ms - 300ms | Poor: > 300ms</small></div>" >> "$INDEX_HTML"
echo "                  <div class=\"mt-3\"><small>Measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.</small></div>" >> "$INDEX_HTML"
echo "                </div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"

echo "              <div class=\"col-md-4\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                  <div class=\"metric-title\">Cumulative Layout Shift (CLS)</div>" >> "$INDEX_HTML"
echo "                  <div class=\"metric-value\" id=\"avg-cls\">Calculating...</div>" >> "$INDEX_HTML"
echo "                  <div class=\"mt-2\"><small class=\"text-muted\">Good: < 0.1 | Needs Improvement: 0.1 - 0.25 | Poor: > 0.25</small></div>" >> "$INDEX_HTML"
echo "                  <div class=\"mt-3\"><small>Measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1 or less.</small></div>" >> "$INDEX_HTML"
echo "                </div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

# Add charts section
echo "      <div class=\"row mb-4\">" >> "$INDEX_HTML"
echo "        <div class=\"col-md-6\">" >> "$INDEX_HTML"
echo "          <div class=\"card h-100\">" >> "$INDEX_HTML"
echo "            <div class=\"card-header d-flex justify-content-between align-items-center\">" >> "$INDEX_HTML"
echo "              <h5 class=\"mb-0\"><i class=\"bi bi-bar-chart me-2\"></i>Desktop vs Mobile Performance</h5>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "            <div class=\"card-body\">" >> "$INDEX_HTML"
echo "              <div class=\"chart-container\">" >> "$INDEX_HTML"
echo "                <canvas id=\"deviceComparisonChart\"></canvas>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"

echo "        <div class=\"col-md-6\">" >> "$INDEX_HTML"
echo "          <div class=\"card h-100\">" >> "$INDEX_HTML"
echo "            <div class=\"card-header d-flex justify-content-between align-items-center\">" >> "$INDEX_HTML"
echo "              <h5 class=\"mb-0\"><i class=\"bi bi-graph-up me-2\"></i>Page Performance Comparison</h5>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "            <div class=\"card-body\">" >> "$INDEX_HTML"
echo "              <div class=\"chart-container\">" >> "$INDEX_HTML"
echo "                <canvas id=\"pageComparisonChart\"></canvas>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

# Add detailed results table
echo "      <div class=\"col-md-12 mb-4\">" >> "$INDEX_HTML"
echo "        <div class=\"card\">" >> "$INDEX_HTML"
echo "          <div class=\"card-header\">" >> "$INDEX_HTML"
echo "            <h5 class=\"mb-0\"><i class=\"bi bi-table me-2\"></i>Detailed Results</h5>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "          <div class=\"card-body\">" >> "$INDEX_HTML"
echo "            <div class=\"table-responsive\">" >> "$INDEX_HTML"
echo "              <table class=\"table table-striped table-hover\">" >> "$INDEX_HTML"
echo "                <thead class=\"table-light\">" >> "$INDEX_HTML"
echo "                  <tr>" >> "$INDEX_HTML"
echo "                    <th>Page</th>" >> "$INDEX_HTML"
echo "                    <th>Device</th>" >> "$INDEX_HTML"
echo "                    <th>Performance</th>" >> "$INDEX_HTML"
echo "                    <th>Accessibility</th>" >> "$INDEX_HTML"
echo "                    <th>Best Practices</th>" >> "$INDEX_HTML"
echo "                    <th>SEO</th>" >> "$INDEX_HTML"
echo "                    <th>LCP</th>" >> "$INDEX_HTML"
echo "                    <th>FID</th>" >> "$INDEX_HTML"
echo "                    <th>CLS</th>" >> "$INDEX_HTML"
echo "                    <th>Action</th>" >> "$INDEX_HTML"
echo "                  </tr>" >> "$INDEX_HTML"
echo "                </thead>" >> "$INDEX_HTML"
echo "                <tbody id=\"results-table-body\">" >> "$INDEX_HTML"
echo "                  <!-- Table rows will be dynamically populated with JavaScript -->" >> "$INDEX_HTML"
echo "                </tbody>" >> "$INDEX_HTML"
echo "              </table>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

# Add improvement opportunities section with more actionable insights
echo "      <div class=\"col-md-12 mb-4\">" >> "$INDEX_HTML"
echo "        <div class=\"card\">" >> "$INDEX_HTML"
echo "          <div class=\"card-header\">" >> "$INDEX_HTML"
echo "            <h5 class=\"mb-0\"><i class=\"bi bi-lightbulb me-2\"></i>Optimization Opportunities</h5>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "          <div class=\"card-body\">" >> "$INDEX_HTML"
echo "            <div class=\"recommendation action-needed\">" >> "$INDEX_HTML"
echo "              <h4><i class=\"bi bi-exclamation-triangle me-2\"></i>Eliminate render-blocking resources</h4>" >> "$INDEX_HTML"
echo "              <p>Resources that block the first paint of your page can delay user interaction and perception of page load speed.</p>" >> "$INDEX_HTML"
echo "              <p><strong>Action steps:</strong></p>" >> "$INDEX_HTML"
echo "              <ol>" >> "$INDEX_HTML"
echo "                <li>Identify critical CSS and inline it in the <code>&lt;head&gt;</code></li>" >> "$INDEX_HTML"
echo "                <li>Use <code>async</code> or <code>defer</code> attributes for non-critical JavaScript</li>" >> "$INDEX_HTML"
echo "                <li>Consider using resource hints like <code>preconnect</code> and <code>preload</code> for critical assets</li>" >> "$INDEX_HTML"
echo "              </ol>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "            <div class=\"recommendation opportunity\">" >> "$INDEX_HTML"
echo "              <h4><i class=\"bi bi-images me-2\"></i>Properly size and optimize images</h4>" >> "$INDEX_HTML"
echo "              <p>Oversized images require extra bandwidth and processing time, slowing down page loads.</p>" >> "$INDEX_HTML"
echo "              <p><strong>Action steps:</strong></p>" >> "$INDEX_HTML"
echo "              <ol>" >> "$INDEX_HTML"
echo "                <li>Convert all images to modern formats (WebP or AVIF)</li>" >> "$INDEX_HTML"
echo "                <li>Serve responsively sized images using <code>srcset</code> and <code>sizes</code> attributes</li>" >> "$INDEX_HTML"
echo "                <li>Implement compression to reduce file sizes without significant quality loss</li>" >> "$INDEX_HTML"
echo "              </ol>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "            <div class=\"recommendation opportunity\">" >> "$INDEX_HTML"
echo "              <h4><i class=\"bi bi-layers-half me-2\"></i>Defer offscreen images</h4>" >> "$INDEX_HTML"
echo "              <p>Loading images only when they're needed improves initial page load time.</p>" >> "$INDEX_HTML"
echo "              <p><strong>Action steps:</strong></p>" >> "$INDEX_HTML"
echo "              <ol>" >> "$INDEX_HTML"
echo "                <li>Implement native lazy loading with <code>loading=\"lazy\"</code> attribute</li>" >> "$INDEX_HTML"
echo "                <li>Consider using an Intersection Observer for more custom lazy loading behavior</li>" >> "$INDEX_HTML"
echo "                <li>Ensure proper image placeholders to minimize layout shifts during loading</li>" >> "$INDEX_HTML"
echo "              </ol>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "            <div class=\"recommendation action-needed\">" >> "$INDEX_HTML"
echo "              <h4><i class=\"bi bi-code-slash me-2\"></i>Reduce JavaScript execution time</h4>" >> "$INDEX_HTML"
echo "              <p>Heavy JavaScript can block the main thread and delay interactivity.</p>" >> "$INDEX_HTML"
echo "              <p><strong>Action steps:</strong></p>" >> "$INDEX_HTML"
echo "              <ol>" >> "$INDEX_HTML"
echo "                <li>Audit and remove unused JavaScript code</li>" >> "$INDEX_HTML"
echo "                <li>Split code into smaller chunks and load on demand</li>" >> "$INDEX_HTML"
echo "                <li>Use Web Workers for CPU-intensive tasks that would block the main thread</li>" >> "$INDEX_HTML"
echo "                <li>Implement code-splitting in your bundler configuration</li>" >> "$INDEX_HTML"
echo "              </ol>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "            <div class=\"text-center mt-4\">" >> "$INDEX_HTML"
echo "              <a href=\"performance-optimization-plan.md\" class=\"btn-primary\"><i class=\"bi bi-file-earmark-text me-2\"></i>View Full Optimization Plan</a>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

# Add a new section for understanding the metrics
echo "      <div class=\"col-md-12 mb-4\">" >> "$INDEX_HTML"
echo "        <div class=\"card\">" >> "$INDEX_HTML"
echo "          <div class=\"card-header\">" >> "$INDEX_HTML"
echo "            <h5 class=\"mb-0\"><i class=\"bi bi-info-circle me-2\"></i>Understanding Performance Metrics</h5>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "          <div class=\"card-body\">" >> "$INDEX_HTML"
echo "            <p class=\"mb-4\">Each metric provides insights into different aspects of user experience:</p>" >> "$INDEX_HTML"
echo "            <div class=\"metrics-grid\">" >> "$INDEX_HTML"
echo "              <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-title\">Performance Score</div>" >> "$INDEX_HTML"
echo "                <div class=\"metric-description\">Overall score based on lab data for loading speed, interactivity, and visual stability. Higher is better.</div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-title\">First Contentful Paint (FCP)</div>" >> "$INDEX_HTML"
echo "                <div class=\"metric-description\">Measures the time from navigation to when the browser renders the first bit of content.</div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-title\">Speed Index (SI)</div>" >> "$INDEX_HTML"
echo "                <div class=\"metric-description\">Shows how quickly content is visually displayed during page load. Lower is better.</div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-title\">Time to Interactive (TTI)</div>" >> "$INDEX_HTML"
echo "                <div class=\"metric-description\">Measures how long it takes for a page to become fully interactive. Lower is better.</div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-title\">Total Blocking Time (TBT)</div>" >> "$INDEX_HTML"
echo "                <div class=\"metric-description\">Sum of time periods between FCP and TTI when the main thread was blocked. Lower is better.</div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-card\">" >> "$INDEX_HTML"
echo "                <div class=\"metric-title\">Accessibility Score</div>" >> "$INDEX_HTML"
echo "                <div class=\"metric-description\">How accessible your content is to all users, including those with disabilities.</div>" >> "$INDEX_HTML"
echo "              </div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

echo "    </div>" >> "$INDEX_HTML"
echo "  </div>" >> "$INDEX_HTML"

# Add footer
echo "  <footer class=\"footer\">" >> "$INDEX_HTML"
echo "    <div class=\"container\">" >> "$INDEX_HTML"
echo "      <p><i class=\"bi bi-speedometer2 me-2\"></i>Generated on $CURRENT_DATE by Lighthouse CI GitHub Action</p>" >> "$INDEX_HTML"
echo "      <p><small>Lighthouse is an open-source, automated tool for improving the quality of web pages. Learn more at <a href=\"https://developers.google.com/web/tools/lighthouse\" target=\"_blank\">Google Developers</a>.</small></p>" >> "$INDEX_HTML"
echo "    </div>" >> "$INDEX_HTML"
echo "  </footer>" >> "$INDEX_HTML"

# Add JavaScript for data loading and visualization
echo "  <script>" >> "$INDEX_HTML"
echo "    // Performance data from the tests" >> "$INDEX_HTML"
echo "    const performanceData = {" >> "$INDEX_HTML"
echo "      pages: []," >> "$INDEX_HTML"
echo "      date: '$CURRENT_DATE'" >> "$INDEX_HTML"
echo "    };" >> "$INDEX_HTML"

# Add placeholder data for fallback
echo "    // Initialize with fallback data in case live data can't be loaded" >> "$INDEX_HTML"
echo "    const fallbackData = [" >> "$INDEX_HTML"
echo "      {" >> "$INDEX_HTML"
echo "        name: 'homepage'," >> "$INDEX_HTML"
echo "        url: 'https://curalife.com/'," >> "$INDEX_HTML"
echo "        desktop: {" >> "$INDEX_HTML"
echo "          performance: 85," >> "$INDEX_HTML"
echo "          accessibility: 92," >> "$INDEX_HTML"
echo "          bestPractices: 88," >> "$INDEX_HTML"
echo "          seo: 95," >> "$INDEX_HTML"
echo "          metrics: {" >> "$INDEX_HTML"
echo "            LCP: 2300," >> "$INDEX_HTML"
echo "            FID: 20," >> "$INDEX_HTML"
echo "            CLS: 0.05" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }," >> "$INDEX_HTML"
echo "        mobile: {" >> "$INDEX_HTML"
echo "          performance: 75," >> "$INDEX_HTML"
echo "          accessibility: 90," >> "$INDEX_HTML"
echo "          bestPractices: 85," >> "$INDEX_HTML"
echo "          seo: 93," >> "$INDEX_HTML"
echo "          metrics: {" >> "$INDEX_HTML"
echo "            LCP: 3100," >> "$INDEX_HTML"
echo "            FID: 90," >> "$INDEX_HTML"
echo "            CLS: 0.12" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      }," >> "$INDEX_HTML"
echo "      {" >> "$INDEX_HTML"
echo "        name: 'product'," >> "$INDEX_HTML"
echo "        url: 'https://curalife.com/products/curalin'," >> "$INDEX_HTML"
echo "        desktop: {" >> "$INDEX_HTML"
echo "          performance: 82," >> "$INDEX_HTML"
echo "          accessibility: 90," >> "$INDEX_HTML"
echo "          bestPractices: 85," >> "$INDEX_HTML"
echo "          seo: 92," >> "$INDEX_HTML"
echo "          metrics: {" >> "$INDEX_HTML"
echo "            LCP: 2500," >> "$INDEX_HTML"
echo "            FID: 25," >> "$INDEX_HTML"
echo "            CLS: 0.08" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }," >> "$INDEX_HTML"
echo "        mobile: {" >> "$INDEX_HTML"
echo "          performance: 70," >> "$INDEX_HTML"
echo "          accessibility: 88," >> "$INDEX_HTML"
echo "          bestPractices: 83," >> "$INDEX_HTML"
echo "          seo: 90," >> "$INDEX_HTML"
echo "          metrics: {" >> "$INDEX_HTML"
echo "            LCP: 3300," >> "$INDEX_HTML"
echo "            FID: 110," >> "$INDEX_HTML"
echo "            CLS: 0.15" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "    ];" >> "$INDEX_HTML"

# Add formatting functions
echo "    // Function to format scores with appropriate styling" >> "$INDEX_HTML"
echo "    function formatScore(score) {" >> "$INDEX_HTML"
echo "      const numScore = parseInt(score);" >> "$INDEX_HTML"
echo "      let badgeClass = 'badge-below75';" >> "$INDEX_HTML"
echo "      if (numScore >= 90) {" >> "$INDEX_HTML"
echo "        badgeClass = 'badge-90plus';" >> "$INDEX_HTML"
echo "      } else if (numScore >= 75) {" >> "$INDEX_HTML"
echo "        badgeClass = 'badge-75to89';" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "      return \`<span class=\"badge badge-score \${badgeClass}\">\${score}</span>\`;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

echo "    // Function to format time values" >> "$INDEX_HTML"
echo "    function formatTime(timeMs) {" >> "$INDEX_HTML"
echo "      return (timeMs / 1000).toFixed(2) + 's';" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

echo "    // Function to classify CWV metrics" >> "$INDEX_HTML"
echo "    function getMetricClass(metric, value) {" >> "$INDEX_HTML"
echo "      if (metric === 'LCP') {" >> "$INDEX_HTML"
echo "        return value < 2500 ? 'good' : (value < 4000 ? 'average' : 'poor');" >> "$INDEX_HTML"
echo "      } else if (metric === 'FID' || metric === 'TBT') {" >> "$INDEX_HTML"
echo "        return value < 100 ? 'good' : (value < 300 ? 'average' : 'poor');" >> "$INDEX_HTML"
echo "      } else if (metric === 'CLS') {" >> "$INDEX_HTML"
echo "        return value < 0.1 ? 'good' : (value < 0.25 ? 'average' : 'poor');" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "      return '';" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

# Add data loading function
echo "    // Fetch actual JSON data from report files" >> "$INDEX_HTML"
echo "    async function loadReportData() {" >> "$INDEX_HTML"
echo "      try {" >> "$INDEX_HTML"
echo "        // Attempt to fetch actual metrics data for each page" >> "$INDEX_HTML"
echo "        const pages = [];" >> "$INDEX_HTML"
echo "        const pageNames = ['homepage', 'product'];" >> "$INDEX_HTML"
echo "        let loadedActualData = false;" >> "$INDEX_HTML"
echo "        " >> "$INDEX_HTML"
echo "        for (const pageName of pageNames) {" >> "$INDEX_HTML"
echo "          try {" >> "$INDEX_HTML"
echo "            const response = await fetch(`./\${pageName}-details/metrics-values.json`);" >> "$INDEX_HTML"
echo "            if (response.ok) {" >> "$INDEX_HTML"
echo "              const data = await response.json();" >> "$INDEX_HTML"
echo "              pages.push(data);" >> "$INDEX_HTML"
echo "              loadedActualData = true;" >> "$INDEX_HTML"
echo "              console.log(`Loaded data for \${pageName}:`, data);" >> "$INDEX_HTML"
echo "            } else {" >> "$INDEX_HTML"
echo "              console.warn(`Could not load data for \${pageName}, using fallback data`);" >> "$INDEX_HTML"
echo "              // Use fallback data for this page" >> "$INDEX_HTML"
echo "              const fallbackPage = fallbackData.find(p => p.name === pageName);" >> "$INDEX_HTML"
echo "              if (fallbackPage) {" >> "$INDEX_HTML"
echo "                pages.push(fallbackPage);" >> "$INDEX_HTML"
echo "              }" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          } catch (err) {" >> "$INDEX_HTML"
echo "            console.warn(`Error loading data for \${pageName}:`, err);" >> "$INDEX_HTML"
echo "            // Use fallback data for this page" >> "$INDEX_HTML"
echo "            const fallbackPage = fallbackData.find(p => p.name === pageName);" >> "$INDEX_HTML"
echo "            if (fallbackPage) {" >> "$INDEX_HTML"
echo "              pages.push(fallbackPage);" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "        " >> "$INDEX_HTML"
echo "        if (pages.length > 0) {" >> "$INDEX_HTML"
echo "          performanceData.pages = pages;" >> "$INDEX_HTML"
echo "        } else {" >> "$INDEX_HTML"
echo "          // If no pages were loaded (unlikely), use all fallback data" >> "$INDEX_HTML"
echo "          performanceData.pages = fallbackData;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "        " >> "$INDEX_HTML"
echo "        // Add warning banner if using fallback data" >> "$INDEX_HTML"
echo "        if (!loadedActualData) {" >> "$INDEX_HTML"
echo "          const warningBanner = document.createElement('div');" >> "$INDEX_HTML"
echo "          warningBanner.className = 'alert alert-warning';" >> "$INDEX_HTML"
echo "          warningBanner.innerHTML = '<strong>Note:</strong> Using placeholder data. Actual Lighthouse results could not be loaded.';" >> "$INDEX_HTML"
echo "          document.querySelector('.dashboard-header').after(warningBanner);" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "        " >> "$INDEX_HTML"
echo "        updateDashboard();" >> "$INDEX_HTML"
echo "      } catch (error) {" >> "$INDEX_HTML"
echo "        console.error('Error loading report data:', error);" >> "$INDEX_HTML"
echo "        // Still update with fallback data if there's an error" >> "$INDEX_HTML"
echo "        performanceData.pages = fallbackData;" >> "$INDEX_HTML"
echo "        updateDashboard();" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

echo "    // Update the dashboard with the loaded data" >> "$INDEX_HTML"
echo "    function updateDashboard() {" >> "$INDEX_HTML"
echo "      // Calculate averages" >> "$INDEX_HTML"
echo "      const totals = {" >> "$INDEX_HTML"
echo "        performance: 0, accessibility: 0, bestPractices: 0, seo: 0," >> "$INDEX_HTML"
echo "        lcp: 0, fid: 0, cls: 0, count: 0" >> "$INDEX_HTML"
echo "      };" >> "$INDEX_HTML"

echo "      // Process all data and compute averages" >> "$INDEX_HTML"
echo "      performanceData.pages.forEach(page => {" >> "$INDEX_HTML"
echo "        // Count desktop metrics" >> "$INDEX_HTML"
echo "        if (page.desktop) {" >> "$INDEX_HTML"
echo "          totals.performance += page.desktop.performance;" >> "$INDEX_HTML"
echo "          totals.accessibility += page.desktop.accessibility;" >> "$INDEX_HTML"
echo "          totals.bestPractices += page.desktop.bestPractices;" >> "$INDEX_HTML"
echo "          totals.seo += page.desktop.seo;" >> "$INDEX_HTML"
echo "          totals.lcp += page.desktop.metrics.LCP;" >> "$INDEX_HTML"
echo "          totals.fid += page.desktop.metrics.FID;" >> "$INDEX_HTML"
echo "          totals.cls += page.desktop.metrics.CLS;" >> "$INDEX_HTML"
echo "          totals.count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"

echo "        // Count mobile metrics" >> "$INDEX_HTML"
echo "        if (page.mobile) {" >> "$INDEX_HTML"
echo "          totals.performance += page.mobile.performance;" >> "$INDEX_HTML"
echo "          totals.accessibility += page.mobile.accessibility;" >> "$INDEX_HTML"
echo "          totals.bestPractices += page.mobile.bestPractices;" >> "$INDEX_HTML"
echo "          totals.seo += page.mobile.seo;" >> "$INDEX_HTML"
echo "          totals.lcp += page.mobile.metrics.LCP;" >> "$INDEX_HTML"
echo "          totals.fid += page.mobile.metrics.FID;" >> "$INDEX_HTML"
echo "          totals.cls += page.mobile.metrics.CLS;" >> "$INDEX_HTML"
echo "          totals.count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"

echo "      // Update summary metrics" >> "$INDEX_HTML"
echo "      if (totals.count > 0) {" >> "$INDEX_HTML"
echo "        document.getElementById('avg-perf').textContent = Math.round(totals.performance / totals.count) + '%';" >> "$INDEX_HTML"
echo "        document.getElementById('avg-a11y').textContent = Math.round(totals.accessibility / totals.count) + '%';" >> "$INDEX_HTML"
echo "        document.getElementById('avg-bp').textContent = Math.round(totals.bestPractices / totals.count) + '%';" >> "$INDEX_HTML"
echo "        document.getElementById('avg-seo').textContent = Math.round(totals.seo / totals.count) + '%';" >> "$INDEX_HTML"

echo "        const avgLcp = Math.round(totals.lcp / totals.count);" >> "$INDEX_HTML"
echo "        const avgFid = Math.round(totals.fid / totals.count);" >> "$INDEX_HTML"
echo "        const avgCls = (totals.cls / totals.count).toFixed(2);" >> "$INDEX_HTML"

echo "        const lcpEl = document.getElementById('avg-lcp');" >> "$INDEX_HTML"
echo "        lcpEl.textContent = (avgLcp / 1000).toFixed(2) + 's';" >> "$INDEX_HTML"
echo "        lcpEl.classList.add(getMetricClass('LCP', avgLcp));" >> "$INDEX_HTML"

echo "        const fidEl = document.getElementById('avg-fid');" >> "$INDEX_HTML"
echo "        fidEl.textContent = avgFid + 'ms';" >> "$INDEX_HTML"
echo "        fidEl.classList.add(getMetricClass('FID', avgFid));" >> "$INDEX_HTML"

echo "        const clsEl = document.getElementById('avg-cls');" >> "$INDEX_HTML"
echo "        clsEl.textContent = avgCls;" >> "$INDEX_HTML"
echo "        clsEl.classList.add(getMetricClass('CLS', avgCls));" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"

# Add table population code
echo "      // Populate the results table" >> "$INDEX_HTML"
echo "      const tableBody = document.getElementById('results-table-body');" >> "$INDEX_HTML"
echo "      tableBody.innerHTML = '';" >> "$INDEX_HTML"

echo "      performanceData.pages.forEach(page => {" >> "$INDEX_HTML"
echo "        // Add desktop row" >> "$INDEX_HTML"
echo "        if (page.desktop) {" >> "$INDEX_HTML"
echo "          const tr = document.createElement('tr');" >> "$INDEX_HTML"
echo "          tr.innerHTML = \`" >> "$INDEX_HTML"
echo "            <td>\${page.name}</td>" >> "$INDEX_HTML"
echo "            <td>Desktop</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.desktop.performance)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.desktop.accessibility)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.desktop.bestPractices)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.desktop.seo)}</td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('LCP', page.desktop.metrics.LCP)}\">\${formatTime(page.desktop.metrics.LCP)}</span></td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('FID', page.desktop.metrics.FID)}\">\${page.desktop.metrics.FID}ms</span></td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('CLS', page.desktop.metrics.CLS)}\">\${page.desktop.metrics.CLS}</span></td>" >> "$INDEX_HTML"
echo "            <td><a href=\"./\${performanceData.date}/\${page.name}/desktop.html\" class=\"btn-detail\">View Report</a></td>" >> "$INDEX_HTML"
echo "          \`;" >> "$INDEX_HTML"
echo "          tableBody.appendChild(tr);" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"

echo "        // Add mobile row" >> "$INDEX_HTML"
echo "        if (page.mobile) {" >> "$INDEX_HTML"
echo "          const tr = document.createElement('tr');" >> "$INDEX_HTML"
echo "          tr.innerHTML = \`" >> "$INDEX_HTML"
echo "            <td>\${page.name}</td>" >> "$INDEX_HTML"
echo "            <td>Mobile</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.mobile.performance)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.mobile.accessibility)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.mobile.bestPractices)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.mobile.seo)}</td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('LCP', page.mobile.metrics.LCP)}\">\${formatTime(page.mobile.metrics.LCP)}</span></td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('FID', page.mobile.metrics.FID)}\">\${page.mobile.metrics.FID}ms</span></td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('CLS', page.mobile.metrics.CLS)}\">\${page.mobile.metrics.CLS}</span></td>" >> "$INDEX_HTML"
echo "            <td><a href=\"./\${performanceData.date}/\${page.name}/mobile.html\" class=\"btn-detail\">View Report</a></td>" >> "$INDEX_HTML"
echo "          \`;" >> "$INDEX_HTML"
echo "          tableBody.appendChild(tr);" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"

# Add chart generation functions
echo "      // Create the device comparison chart" >> "$INDEX_HTML"
echo "      createDeviceComparisonChart();" >> "$INDEX_HTML"
echo "      createPageComparisonChart();" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

echo "    // Create the device comparison chart" >> "$INDEX_HTML"
echo "    function createDeviceComparisonChart() {" >> "$INDEX_HTML"
echo "      const ctx = document.getElementById('deviceComparisonChart').getContext('2d');" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      // Calculate average desktop and mobile scores" >> "$INDEX_HTML"
echo "      const desktopScores = { perf: 0, a11y: 0, bp: 0, seo: 0, count: 0 };" >> "$INDEX_HTML"
echo "      const mobileScores = { perf: 0, a11y: 0, bp: 0, seo: 0, count: 0 };" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      performanceData.pages.forEach(page => {" >> "$INDEX_HTML"
echo "        if (page.desktop) {" >> "$INDEX_HTML"
echo "          desktopScores.perf += page.desktop.performance;" >> "$INDEX_HTML"
echo "          desktopScores.a11y += page.desktop.accessibility;" >> "$INDEX_HTML"
echo "          desktopScores.bp += page.desktop.bestPractices;" >> "$INDEX_HTML"
echo "          desktopScores.seo += page.desktop.seo;" >> "$INDEX_HTML"
echo "          desktopScores.count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "        if (page.mobile) {" >> "$INDEX_HTML"
echo "          mobileScores.perf += page.mobile.performance;" >> "$INDEX_HTML"
echo "          mobileScores.a11y += page.mobile.accessibility;" >> "$INDEX_HTML"
echo "          mobileScores.bp += page.mobile.bestPractices;" >> "$INDEX_HTML"
echo "          mobileScores.seo += page.mobile.seo;" >> "$INDEX_HTML"
echo "          mobileScores.count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      const avgDesktopPerf = desktopScores.count > 0 ? Math.round(desktopScores.perf / desktopScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgDesktopA11y = desktopScores.count > 0 ? Math.round(desktopScores.a11y / desktopScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgDesktopBP = desktopScores.count > 0 ? Math.round(desktopScores.bp / desktopScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgDesktopSEO = desktopScores.count > 0 ? Math.round(desktopScores.seo / desktopScores.count) : 0;" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      const avgMobilePerf = mobileScores.count > 0 ? Math.round(mobileScores.perf / mobileScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgMobileA11y = mobileScores.count > 0 ? Math.round(mobileScores.a11y / mobileScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgMobileBP = mobileScores.count > 0 ? Math.round(mobileScores.bp / mobileScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgMobileSEO = mobileScores.count > 0 ? Math.round(mobileScores.seo / mobileScores.count) : 0;" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      const deviceChart = new Chart(ctx, {" >> "$INDEX_HTML"
echo "        type: 'bar'," >> "$INDEX_HTML"
echo "        data: {" >> "$INDEX_HTML"
echo "          labels: ['Performance', 'Accessibility', 'Best Practices', 'SEO']," >> "$INDEX_HTML"
echo "          datasets: [" >> "$INDEX_HTML"
echo "            {" >> "$INDEX_HTML"
echo "              label: 'Desktop'," >> "$INDEX_HTML"
echo "              data: [avgDesktopPerf, avgDesktopA11y, avgDesktopBP, avgDesktopSEO]," >> "$INDEX_HTML"
echo "              backgroundColor: 'rgba(54, 162, 235, 0.6)'," >> "$INDEX_HTML"
echo "              borderColor: 'rgb(54, 162, 235)'," >> "$INDEX_HTML"
echo "              borderWidth: 1" >> "$INDEX_HTML"
echo "            }," >> "$INDEX_HTML"
echo "            {" >> "$INDEX_HTML"
echo "              label: 'Mobile'," >> "$INDEX_HTML"
echo "              data: [avgMobilePerf, avgMobileA11y, avgMobileBP, avgMobileSEO]," >> "$INDEX_HTML"
echo "              backgroundColor: 'rgba(255, 99, 132, 0.6)'," >> "$INDEX_HTML"
echo "              borderColor: 'rgb(255, 99, 132)'," >> "$INDEX_HTML"
echo "              borderWidth: 1" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          ]" >> "$INDEX_HTML"
echo "        }," >> "$INDEX_HTML"
echo "        options: {" >> "$INDEX_HTML"
echo "          responsive: true," >> "$INDEX_HTML"
echo "          maintainAspectRatio: false," >> "$INDEX_HTML"
echo "          scales: {" >> "$INDEX_HTML"
echo "            y: {" >> "$INDEX_HTML"
echo "              beginAtZero: true," >> "$INDEX_HTML"
echo "              max: 100," >> "$INDEX_HTML"
echo "              title: {" >> "$INDEX_HTML"
echo "                display: true," >> "$INDEX_HTML"
echo "                text: 'Score (%)'" >> "$INDEX_HTML"
echo "              }" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          }," >> "$INDEX_HTML"
echo "          plugins: {" >> "$INDEX_HTML"
echo "            legend: {" >> "$INDEX_HTML"
echo "              position: 'top'" >> "$INDEX_HTML"
echo "            }," >> "$INDEX_HTML"
echo "            title: {" >> "$INDEX_HTML"
echo "              display: false" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

echo "    // Create the page comparison chart" >> "$INDEX_HTML"
echo "    function createPageComparisonChart() {" >> "$INDEX_HTML"
echo "      const ctx = document.getElementById('pageComparisonChart').getContext('2d');" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      // Prepare data for each page" >> "$INDEX_HTML"
echo "      const pageNames = [];" >> "$INDEX_HTML"
echo "      const pagePerformance = [];" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      performanceData.pages.forEach(page => {" >> "$INDEX_HTML"
echo "        pageNames.push(page.name);" >> "$INDEX_HTML"
echo "        // Average desktop and mobile performance if both exist, otherwise use what's available" >> "$INDEX_HTML"
echo "        let score = 0;" >> "$INDEX_HTML"
echo "        let count = 0;" >> "$INDEX_HTML"
echo "        if (page.desktop) {" >> "$INDEX_HTML"
echo "          score += page.desktop.performance;" >> "$INDEX_HTML"
echo "          count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "        if (page.mobile) {" >> "$INDEX_HTML"
echo "          score += page.mobile.performance;" >> "$INDEX_HTML"
echo "          count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "        pagePerformance.push(count > 0 ? Math.round(score / count) : 0);" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      const pageChart = new Chart(ctx, {" >> "$INDEX_HTML"
echo "        type: 'bar'," >> "$INDEX_HTML"
echo "        data: {" >> "$INDEX_HTML"
echo "          labels: pageNames," >> "$INDEX_HTML"
echo "          datasets: [" >> "$INDEX_HTML"
echo "            {" >> "$INDEX_HTML"
echo "              label: 'Performance Score'," >> "$INDEX_HTML"
echo "              data: pagePerformance," >> "$INDEX_HTML"
echo "              backgroundColor: pagePerformance.map(score => {" >> "$INDEX_HTML"
echo "                if (score >= 90) return 'rgba(75, 192, 192, 0.6)';" >> "$INDEX_HTML"
echo "                if (score >= 75) return 'rgba(255, 206, 86, 0.6)';" >> "$INDEX_HTML"
echo "                return 'rgba(255, 99, 132, 0.6)';" >> "$INDEX_HTML"
echo "              })," >> "$INDEX_HTML"
echo "              borderColor: pagePerformance.map(score => {" >> "$INDEX_HTML"
echo "                if (score >= 90) return 'rgb(75, 192, 192)';" >> "$INDEX_HTML"
echo "                if (score >= 75) return 'rgb(255, 206, 86)';" >> "$INDEX_HTML"
echo "                return 'rgb(255, 99, 132)';" >> "$INDEX_HTML"
echo "              })," >> "$INDEX_HTML"
echo "              borderWidth: 1" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          ]" >> "$INDEX_HTML"
echo "        }," >> "$INDEX_HTML"
echo "        options: {" >> "$INDEX_HTML"
echo "          responsive: true," >> "$INDEX_HTML"
echo "          maintainAspectRatio: false," >> "$INDEX_HTML"
echo "          scales: {" >> "$INDEX_HTML"
echo "            y: {" >> "$INDEX_HTML"
echo "              beginAtZero: true," >> "$INDEX_HTML"
echo "              max: 100," >> "$INDEX_HTML"
echo "              title: {" >> "$INDEX_HTML"
echo "                display: true," >> "$INDEX_HTML"
echo "                text: 'Score (%)'" >> "$INDEX_HTML"
echo "              }" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          }," >> "$INDEX_HTML"
echo "          plugins: {" >> "$INDEX_HTML"
echo "            legend: {" >> "$INDEX_HTML"
echo "              display: false" >> "$INDEX_HTML"
echo "            }," >> "$INDEX_HTML"
echo "            title: {" >> "$INDEX_HTML"
echo "              display: false" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

# Add document load event handler
echo "    // Load data when the page loads" >> "$INDEX_HTML"
echo "    document.addEventListener('DOMContentLoaded', loadReportData);" >> "$INDEX_HTML"
echo "  </script>" >> "$INDEX_HTML"
echo "</body>" >> "$INDEX_HTML"
echo "</html>" >> "$INDEX_HTML"

echo "Dashboard file generated at $INDEX_HTML"

# After the file is created, copy it to other locations for GitHub Pages
echo "Copying dashboard to additional locations for GitHub Pages..."

# Create dashboards directory if it doesn't exist
mkdir -p dashboards

# Copy to dashboards directory
cp "$INDEX_HTML" "dashboards/index.html"
echo "Copied to dashboards/index.html"

# Copy to root directory if parent directories exist
if [ -d "../lighthouse-results" ]; then
  cp "$INDEX_HTML" "../lighthouse-results/index.html"
  echo "Copied to ../lighthouse-results/index.html"
fi

# Create .nojekyll file to prevent GitHub Pages from using Jekyll
touch performance-reports/.nojekyll
touch dashboards/.nojekyll
if [ -d "../lighthouse-results" ]; then
  touch "../lighthouse-results/.nojekyll"
fi

echo "Dashboard generation complete with additional copies for GitHub Pages!"