#!/bin/bash

# This script generates the main performance dashboard HTML file
# Usage: ./generate-dashboard.sh [CURRENT_DATE]

# Get parameters
CURRENT_DATE=$1

# Exit if required parameters are missing
if [ -z "$CURRENT_DATE" ]; then
  echo "Error: Missing required parameters"
  echo "Usage: ./generate-dashboard.sh [CURRENT_DATE]"
  exit 1
fi

# Create the main index.html file
INDEX_HTML="performance-reports/index.html"
echo "Creating index HTML file at $INDEX_HTML"

# Create HTML header and start of body
echo "<!DOCTYPE html>" > "$INDEX_HTML"
echo "<html lang=\"en\">" >> "$INDEX_HTML"
echo "<head>" >> "$INDEX_HTML"
echo "  <meta charset=\"UTF-8\">" >> "$INDEX_HTML"
echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> "$INDEX_HTML"
echo "  <title>Lighthouse Performance Reports</title>" >> "$INDEX_HTML"
echo "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">" >> "$INDEX_HTML"
echo "  <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>" >> "$INDEX_HTML"
echo "  <style>" >> "$INDEX_HTML"
echo "    body { font-family: 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif; line-height: 1.6; max-width: 1400px; margin: 0 auto; padding: 20px; background-color: #f8f9fa; }" >> "$INDEX_HTML"
echo "    h1, h2, h3 { color: #2c3e50; margin-top: 1.5rem; }" >> "$INDEX_HTML"
echo "    .header { background: linear-gradient(90deg, #4285f4, #34a853); color: white; padding: 2rem; border-radius: 10px; margin-bottom: 2rem; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }" >> "$INDEX_HTML"
echo "    .card { background: white; border-radius: 10px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); transition: transform 0.2s; }" >> "$INDEX_HTML"
echo "    .card:hover { transform: translateY(-5px); box-shadow: 0 4px 15px rgba(0,0,0,0.1); }" >> "$INDEX_HTML"
echo "    .metric-card { text-align: center; padding: 1.5rem; }" >> "$INDEX_HTML"
echo "    .metric-value { font-size: 2.5rem; font-weight: bold; margin-bottom: 5px; }" >> "$INDEX_HTML"
echo "    .metric-label { font-size: 0.9rem; color: #6c757d; text-transform: uppercase; letter-spacing: 1px; }" >> "$INDEX_HTML"
echo "    .pill { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 50px; font-size: 0.8rem; font-weight: 500; margin-right: 5px; }" >> "$INDEX_HTML"
echo "    .good { background-color: #d4edda; color: #155724; }" >> "$INDEX_HTML"
echo "    .average { background-color: #fff3cd; color: #856404; }" >> "$INDEX_HTML"
echo "    .poor { background-color: #f8d7da; color: #721c24; }" >> "$INDEX_HTML"
echo "    .chart-container { position: relative; height: 300px; margin-bottom: 2rem; }" >> "$INDEX_HTML"
echo "    .table { margin-top: 1.5rem; }" >> "$INDEX_HTML"
echo "    .table th { background-color: #f8f9fa; }" >> "$INDEX_HTML"
echo "    .badge-score { font-size: 1rem; padding: 0.3rem 0.6rem; border-radius: 50px; }" >> "$INDEX_HTML"
echo "    .badge-90plus { background-color: #28a745; color: white; }" >> "$INDEX_HTML"
echo "    .badge-75to89 { background-color: #ffc107; color: #212529; }" >> "$INDEX_HTML"
echo "    .badge-below75 { background-color: #dc3545; color: white; }" >> "$INDEX_HTML"
echo "    .recommendation { padding: 1rem; margin-bottom: 1rem; border-left: 4px solid #4285f4; background-color: #f8f9fa; }" >> "$INDEX_HTML"
echo "    .btn-detail { background-color: #4285f4; color: white; border: none; padding: 0.5rem 1rem; border-radius: 4px; text-decoration: none; display: inline-block; }" >> "$INDEX_HTML"
echo "    .btn-detail:hover { background-color: #3367d6; color: white; text-decoration: none; }" >> "$INDEX_HTML"
echo "    footer { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid #dee2e6; color: #6c757d; text-align: center; font-size: 0.9rem; }" >> "$INDEX_HTML"
echo "  </style>" >> "$INDEX_HTML"
echo "</head>" >> "$INDEX_HTML"
echo "<body>" >> "$INDEX_HTML"

# Add header section
echo "  <div class=\"header\">" >> "$INDEX_HTML"
echo "    <h1><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" fill=\"currentColor\" class=\"bi bi-speedometer2\" viewBox=\"0 0 16 16\"><path d=\"M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z\"/><path fill-rule=\"evenodd\" d=\"M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z\"/></svg> Lighthouse Performance Dashboard</h1>" >> "$INDEX_HTML"
echo "    <p>Tracking website performance metrics from automated Lighthouse tests. Last updated: $CURRENT_DATE</p>" >> "$INDEX_HTML"
echo "  </div>" >> "$INDEX_HTML"

# Add container for content
echo "  <div class=\"container-fluid p-0\">" >> "$INDEX_HTML"
echo "    <div class=\"row\">" >> "$INDEX_HTML"

# Add metrics overview section
echo "      <div class=\"col-md-12 mb-4\">" >> "$INDEX_HTML"
echo "        <h2>Performance Overview</h2>" >> "$INDEX_HTML"
echo "        <div class=\"row\">" >> "$INDEX_HTML"

# Add average score metrics
echo "          <div class=\"col-md-3\">" >> "$INDEX_HTML"
echo "            <div class=\"card metric-card\">" >> "$INDEX_HTML"
echo "              <div class=\"metric-value\" id=\"avg-perf\">Calculating...</div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-label\">Average Performance Score</div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"

echo "          <div class=\"col-md-3\">" >> "$INDEX_HTML"
echo "            <div class=\"card metric-card\">" >> "$INDEX_HTML"
echo "              <div class=\"metric-value\" id=\"avg-a11y\">Calculating...</div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-label\">Average Accessibility Score</div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"

echo "          <div class=\"col-md-3\">" >> "$INDEX_HTML"
echo "            <div class=\"card metric-card\">" >> "$INDEX_HTML"
echo "              <div class=\"metric-value\" id=\"avg-bp\">Calculating...</div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-label\">Average Best Practices</div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"

echo "          <div class=\"col-md-3\">" >> "$INDEX_HTML"
echo "            <div class=\"card metric-card\">" >> "$INDEX_HTML"
echo "              <div class=\"metric-value\" id=\"avg-seo\">Calculating...</div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-label\">Average SEO Score</div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

# Add Core Web Vitals section
echo "      <div class=\"col-md-12 mb-4\">" >> "$INDEX_HTML"
echo "        <h2>Core Web Vitals</h2>" >> "$INDEX_HTML"
echo "        <div class=\"row\">" >> "$INDEX_HTML"

echo "          <div class=\"col-md-4\">" >> "$INDEX_HTML"
echo "            <div class=\"card metric-card\">" >> "$INDEX_HTML"
echo "              <div class=\"metric-value\" id=\"avg-lcp\">Calculating...</div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-label\">Largest Contentful Paint (LCP)</div>" >> "$INDEX_HTML"
echo "              <div class=\"mt-2\"><small>Target: < 2.5s</small></div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"

echo "          <div class=\"col-md-4\">" >> "$INDEX_HTML"
echo "            <div class=\"card metric-card\">" >> "$INDEX_HTML"
echo "              <div class=\"metric-value\" id=\"avg-fid\">Calculating...</div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-label\">First Input Delay (FID)</div>" >> "$INDEX_HTML"
echo "              <div class=\"mt-2\"><small>Target: < 100ms</small></div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"

echo "          <div class=\"col-md-4\">" >> "$INDEX_HTML"
echo "            <div class=\"card metric-card\">" >> "$INDEX_HTML"
echo "              <div class=\"metric-value\" id=\"avg-cls\">Calculating...</div>" >> "$INDEX_HTML"
echo "              <div class=\"metric-label\">Cumulative Layout Shift (CLS)</div>" >> "$INDEX_HTML"
echo "              <div class=\"mt-2\"><small>Target: < 0.1</small></div>" >> "$INDEX_HTML"
echo "            </div>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

# Add charts section
echo "      <div class=\"col-md-6 mb-4\">" >> "$INDEX_HTML"
echo "        <div class=\"card\">" >> "$INDEX_HTML"
echo "          <h3>Desktop vs Mobile Performance</h3>" >> "$INDEX_HTML"
echo "          <div class=\"chart-container\">" >> "$INDEX_HTML"
echo "            <canvas id=\"deviceComparisonChart\"></canvas>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

echo "      <div class=\"col-md-6 mb-4\">" >> "$INDEX_HTML"
echo "        <div class=\"card\">" >> "$INDEX_HTML"
echo "          <h3>Page Performance Comparison</h3>" >> "$INDEX_HTML"
echo "          <div class=\"chart-container\">" >> "$INDEX_HTML"
echo "            <canvas id=\"pageComparisonChart\"></canvas>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

# Add detailed results table
echo "      <div class=\"col-md-12 mb-4\">" >> "$INDEX_HTML"
echo "        <h2>Detailed Results</h2>" >> "$INDEX_HTML"
echo "        <div class=\"card\">" >> "$INDEX_HTML"
echo "          <div class=\"table-responsive\">" >> "$INDEX_HTML"
echo "            <table class=\"table table-striped table-hover\">" >> "$INDEX_HTML"
echo "              <thead class=\"table-light\">" >> "$INDEX_HTML"
echo "                <tr>" >> "$INDEX_HTML"
echo "                  <th>Page</th>" >> "$INDEX_HTML"
echo "                  <th>Device</th>" >> "$INDEX_HTML"
echo "                  <th>Performance</th>" >> "$INDEX_HTML"
echo "                  <th>Accessibility</th>" >> "$INDEX_HTML"
echo "                  <th>Best Practices</th>" >> "$INDEX_HTML"
echo "                  <th>SEO</th>" >> "$INDEX_HTML"
echo "                  <th>LCP</th>" >> "$INDEX_HTML"
echo "                  <th>FID</th>" >> "$INDEX_HTML"
echo "                  <th>CLS</th>" >> "$INDEX_HTML"
echo "                  <th>Action</th>" >> "$INDEX_HTML"
echo "                </tr>" >> "$INDEX_HTML"
echo "              </thead>" >> "$INDEX_HTML"
echo "              <tbody id=\"results-table-body\">" >> "$INDEX_HTML"
echo "                <!-- Table rows will be dynamically populated with JavaScript -->" >> "$INDEX_HTML"
echo "              </tbody>" >> "$INDEX_HTML"
echo "            </table>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

# Add improvement opportunities section
echo "      <div class=\"col-md-12 mb-4\">" >> "$INDEX_HTML"
echo "        <h2>Top Improvement Opportunities</h2>" >> "$INDEX_HTML"
echo "        <div class=\"card\">" >> "$INDEX_HTML"
echo "          <div class=\"recommendation\">" >> "$INDEX_HTML"
echo "            <h4>Eliminate render-blocking resources</h4>" >> "$INDEX_HTML"
echo "            <p>Resources that block the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles.</p>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "          <div class=\"recommendation\">" >> "$INDEX_HTML"
echo "            <h4>Properly size images</h4>" >> "$INDEX_HTML"
echo "            <p>Serve images that are appropriately-sized to save cellular data and improve load time. Optimize WebP format for all images.</p>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "          <div class=\"recommendation\">" >> "$INDEX_HTML"
echo "            <h4>Defer offscreen images</h4>" >> "$INDEX_HTML"
echo "            <p>Consider lazy-loading offscreen and hidden images after all critical resources have finished loading.</p>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "          <div class=\"recommendation\">" >> "$INDEX_HTML"
echo "            <h4>Reduce JavaScript execution time</h4>" >> "$INDEX_HTML"
echo "            <p>Consider reducing the time spent parsing, compiling, and executing JS. You may find delivering smaller JS payloads helps.</p>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "          <div class=\"text-center mt-3\">" >> "$INDEX_HTML"
echo "            <a href=\"performance-optimization-plan.md\" class=\"btn-detail\">View Full Optimization Plan</a>" >> "$INDEX_HTML"
echo "          </div>" >> "$INDEX_HTML"
echo "        </div>" >> "$INDEX_HTML"
echo "      </div>" >> "$INDEX_HTML"

echo "    </div>" >> "$INDEX_HTML"
echo "  </div>" >> "$INDEX_HTML"

# Add footer
echo "  <footer>" >> "$INDEX_HTML"
echo "    <p>Generated on $CURRENT_DATE by Lighthouse CI GitHub Action</p>" >> "$INDEX_HTML"
echo "  </footer>" >> "$INDEX_HTML"

# Add JavaScript for data loading and visualization
echo "  <script>" >> "$INDEX_HTML"
echo "    // Performance data from the tests" >> "$INDEX_HTML"
echo "    const performanceData = {" >> "$INDEX_HTML"
echo "      pages: []," >> "$INDEX_HTML"
echo "      date: '$CURRENT_DATE'" >> "$INDEX_HTML"
echo "    };" >> "$INDEX_HTML"

# Add formatting functions
echo "    // Function to format scores with appropriate styling" >> "$INDEX_HTML"
echo "    function formatScore(score) {" >> "$INDEX_HTML"
echo "      const numScore = parseInt(score);" >> "$INDEX_HTML"
echo "      let badgeClass = 'badge-below75';" >> "$INDEX_HTML"
echo "      if (numScore >= 90) {" >> "$INDEX_HTML"
echo "        badgeClass = 'badge-90plus';" >> "$INDEX_HTML"
echo "      } else if (numScore >= 75) {" >> "$INDEX_HTML"
echo "        badgeClass = 'badge-75to89';" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "      return \`<span class=\"badge badge-score \${badgeClass}\">\${score}</span>\`;" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

echo "    // Function to format time values" >> "$INDEX_HTML"
echo "    function formatTime(timeMs) {" >> "$INDEX_HTML"
echo "      return (timeMs / 1000).toFixed(2) + 's';" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

echo "    // Function to classify CWV metrics" >> "$INDEX_HTML"
echo "    function getMetricClass(metric, value) {" >> "$INDEX_HTML"
echo "      if (metric === 'LCP') {" >> "$INDEX_HTML"
echo "        return value < 2500 ? 'good' : (value < 4000 ? 'average' : 'poor');" >> "$INDEX_HTML"
echo "      } else if (metric === 'FID' || metric === 'TBT') {" >> "$INDEX_HTML"
echo "        return value < 100 ? 'good' : (value < 300 ? 'average' : 'poor');" >> "$INDEX_HTML"
echo "      } else if (metric === 'CLS') {" >> "$INDEX_HTML"
echo "        return value < 0.1 ? 'good' : (value < 0.25 ? 'average' : 'poor');" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "      return '';" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

# Add placeholder data
echo "    // Initialize with some placeholder data - will be replaced with actual data" >> "$INDEX_HTML"
echo "    performanceData.pages = [" >> "$INDEX_HTML"
echo "      {" >> "$INDEX_HTML"
echo "        name: 'homepage'," >> "$INDEX_HTML"
echo "        url: 'https://curalife.com/'," >> "$INDEX_HTML"
echo "        desktop: {" >> "$INDEX_HTML"
echo "          performance: 85," >> "$INDEX_HTML"
echo "          accessibility: 92," >> "$INDEX_HTML"
echo "          bestPractices: 88," >> "$INDEX_HTML"
echo "          seo: 95," >> "$INDEX_HTML"
echo "          metrics: {" >> "$INDEX_HTML"
echo "            LCP: 2300," >> "$INDEX_HTML"
echo "            FID: 20," >> "$INDEX_HTML"
echo "            CLS: 0.05" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }," >> "$INDEX_HTML"
echo "        mobile: {" >> "$INDEX_HTML"
echo "          performance: 75," >> "$INDEX_HTML"
echo "          accessibility: 90," >> "$INDEX_HTML"
echo "          bestPractices: 85," >> "$INDEX_HTML"
echo "          seo: 93," >> "$INDEX_HTML"
echo "          metrics: {" >> "$INDEX_HTML"
echo "            LCP: 3100," >> "$INDEX_HTML"
echo "            FID: 90," >> "$INDEX_HTML"
echo "            CLS: 0.12" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      }," >> "$INDEX_HTML"
echo "      {" >> "$INDEX_HTML"
echo "        name: 'product'," >> "$INDEX_HTML"
echo "        url: 'https://curalife.com/products/curalin'," >> "$INDEX_HTML"
echo "        desktop: {" >> "$INDEX_HTML"
echo "          performance: 82," >> "$INDEX_HTML"
echo "          accessibility: 90," >> "$INDEX_HTML"
echo "          bestPractices: 85," >> "$INDEX_HTML"
echo "          seo: 92," >> "$INDEX_HTML"
echo "          metrics: {" >> "$INDEX_HTML"
echo "            LCP: 2500," >> "$INDEX_HTML"
echo "            FID: 25," >> "$INDEX_HTML"
echo "            CLS: 0.08" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }," >> "$INDEX_HTML"
echo "        mobile: {" >> "$INDEX_HTML"
echo "          performance: 70," >> "$INDEX_HTML"
echo "          accessibility: 88," >> "$INDEX_HTML"
echo "          bestPractices: 83," >> "$INDEX_HTML"
echo "          seo: 90," >> "$INDEX_HTML"
echo "          metrics: {" >> "$INDEX_HTML"
echo "            LCP: 3300," >> "$INDEX_HTML"
echo "            FID: 110," >> "$INDEX_HTML"
echo "            CLS: 0.15" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "    ];" >> "$INDEX_HTML"

# Add data loading function
echo "    // Fetch actual JSON data from report files" >> "$INDEX_HTML"
echo "    async function loadReportData() {" >> "$INDEX_HTML"
echo "      try {" >> "$INDEX_HTML"
echo "        // This would typically fetch data from the JSON files" >> "$INDEX_HTML"
echo "        // For now, we'll use the placeholder data and update UI" >> "$INDEX_HTML"
echo "        updateDashboard();" >> "$INDEX_HTML"
echo "      } catch (error) {" >> "$INDEX_HTML"
echo "        console.error('Error loading report data:', error);" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

# Add dashboard update function
echo "    // Update the dashboard with the loaded data" >> "$INDEX_HTML"
echo "    function updateDashboard() {" >> "$INDEX_HTML"
echo "      // Calculate averages" >> "$INDEX_HTML"
echo "      const totals = {" >> "$INDEX_HTML"
echo "        performance: 0, accessibility: 0, bestPractices: 0, seo: 0," >> "$INDEX_HTML"
echo "        lcp: 0, fid: 0, cls: 0, count: 0" >> "$INDEX_HTML"
echo "      };" >> "$INDEX_HTML"

echo "      // Process all data and compute averages" >> "$INDEX_HTML"
echo "      performanceData.pages.forEach(page => {" >> "$INDEX_HTML"
echo "        // Count desktop metrics" >> "$INDEX_HTML"
echo "        if (page.desktop) {" >> "$INDEX_HTML"
echo "          totals.performance += page.desktop.performance;" >> "$INDEX_HTML"
echo "          totals.accessibility += page.desktop.accessibility;" >> "$INDEX_HTML"
echo "          totals.bestPractices += page.desktop.bestPractices;" >> "$INDEX_HTML"
echo "          totals.seo += page.desktop.seo;" >> "$INDEX_HTML"
echo "          totals.lcp += page.desktop.metrics.LCP;" >> "$INDEX_HTML"
echo "          totals.fid += page.desktop.metrics.FID;" >> "$INDEX_HTML"
echo "          totals.cls += page.desktop.metrics.CLS;" >> "$INDEX_HTML"
echo "          totals.count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"

echo "        // Count mobile metrics" >> "$INDEX_HTML"
echo "        if (page.mobile) {" >> "$INDEX_HTML"
echo "          totals.performance += page.mobile.performance;" >> "$INDEX_HTML"
echo "          totals.accessibility += page.mobile.accessibility;" >> "$INDEX_HTML"
echo "          totals.bestPractices += page.mobile.bestPractices;" >> "$INDEX_HTML"
echo "          totals.seo += page.mobile.seo;" >> "$INDEX_HTML"
echo "          totals.lcp += page.mobile.metrics.LCP;" >> "$INDEX_HTML"
echo "          totals.fid += page.mobile.metrics.FID;" >> "$INDEX_HTML"
echo "          totals.cls += page.mobile.metrics.CLS;" >> "$INDEX_HTML"
echo "          totals.count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"

echo "      // Update summary metrics" >> "$INDEX_HTML"
echo "      if (totals.count > 0) {" >> "$INDEX_HTML"
echo "        document.getElementById('avg-perf').textContent = Math.round(totals.performance / totals.count) + '%';" >> "$INDEX_HTML"
echo "        document.getElementById('avg-a11y').textContent = Math.round(totals.accessibility / totals.count) + '%';" >> "$INDEX_HTML"
echo "        document.getElementById('avg-bp').textContent = Math.round(totals.bestPractices / totals.count) + '%';" >> "$INDEX_HTML"
echo "        document.getElementById('avg-seo').textContent = Math.round(totals.seo / totals.count) + '%';" >> "$INDEX_HTML"

echo "        const avgLcp = Math.round(totals.lcp / totals.count);" >> "$INDEX_HTML"
echo "        const avgFid = Math.round(totals.fid / totals.count);" >> "$INDEX_HTML"
echo "        const avgCls = (totals.cls / totals.count).toFixed(2);" >> "$INDEX_HTML"

echo "        const lcpEl = document.getElementById('avg-lcp');" >> "$INDEX_HTML"
echo "        lcpEl.textContent = (avgLcp / 1000).toFixed(2) + 's';" >> "$INDEX_HTML"
echo "        lcpEl.classList.add(getMetricClass('LCP', avgLcp));" >> "$INDEX_HTML"

echo "        const fidEl = document.getElementById('avg-fid');" >> "$INDEX_HTML"
echo "        fidEl.textContent = avgFid + 'ms';" >> "$INDEX_HTML"
echo "        fidEl.classList.add(getMetricClass('FID', avgFid));" >> "$INDEX_HTML"

echo "        const clsEl = document.getElementById('avg-cls');" >> "$INDEX_HTML"
echo "        clsEl.textContent = avgCls;" >> "$INDEX_HTML"
echo "        clsEl.classList.add(getMetricClass('CLS', avgCls));" >> "$INDEX_HTML"
echo "      }" >> "$INDEX_HTML"

# Add table population code
echo "      // Populate the results table" >> "$INDEX_HTML"
echo "      const tableBody = document.getElementById('results-table-body');" >> "$INDEX_HTML"
echo "      tableBody.innerHTML = '';" >> "$INDEX_HTML"

echo "      performanceData.pages.forEach(page => {" >> "$INDEX_HTML"
echo "        // Add desktop row" >> "$INDEX_HTML"
echo "        if (page.desktop) {" >> "$INDEX_HTML"
echo "          const tr = document.createElement('tr');" >> "$INDEX_HTML"
echo "          tr.innerHTML = \`" >> "$INDEX_HTML"
echo "            <td>\${page.name}</td>" >> "$INDEX_HTML"
echo "            <td>Desktop</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.desktop.performance)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.desktop.accessibility)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.desktop.bestPractices)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.desktop.seo)}</td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('LCP', page.desktop.metrics.LCP)}\">\${formatTime(page.desktop.metrics.LCP)}</span></td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('FID', page.desktop.metrics.FID)}\">\${page.desktop.metrics.FID}ms</span></td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('CLS', page.desktop.metrics.CLS)}\">\${page.desktop.metrics.CLS}</span></td>" >> "$INDEX_HTML"
echo "            <td><a href=\"./\${performanceData.date}/\${page.name}/desktop.html\" class=\"btn-detail\">View Report</a></td>" >> "$INDEX_HTML"
echo "          \`;" >> "$INDEX_HTML"
echo "          tableBody.appendChild(tr);" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"

echo "        // Add mobile row" >> "$INDEX_HTML"
echo "        if (page.mobile) {" >> "$INDEX_HTML"
echo "          const tr = document.createElement('tr');" >> "$INDEX_HTML"
echo "          tr.innerHTML = \`" >> "$INDEX_HTML"
echo "            <td>\${page.name}</td>" >> "$INDEX_HTML"
echo "            <td>Mobile</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.mobile.performance)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.mobile.accessibility)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.mobile.bestPractices)}</td>" >> "$INDEX_HTML"
echo "            <td>\${formatScore(page.mobile.seo)}</td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('LCP', page.mobile.metrics.LCP)}\">\${formatTime(page.mobile.metrics.LCP)}</span></td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('FID', page.mobile.metrics.FID)}\">\${page.mobile.metrics.FID}ms</span></td>" >> "$INDEX_HTML"
echo "            <td><span class=\"pill \${getMetricClass('CLS', page.mobile.metrics.CLS)}\">\${page.mobile.metrics.CLS}</span></td>" >> "$INDEX_HTML"
echo "            <td><a href=\"./\${performanceData.date}/\${page.name}/mobile.html\" class=\"btn-detail\">View Report</a></td>" >> "$INDEX_HTML"
echo "          \`;" >> "$INDEX_HTML"
echo "          tableBody.appendChild(tr);" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"

# Add chart generation functions
echo "      // Create the device comparison chart" >> "$INDEX_HTML"
echo "      createDeviceComparisonChart();" >> "$INDEX_HTML"
echo "      createPageComparisonChart();" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

echo "    // Create the device comparison chart" >> "$INDEX_HTML"
echo "    function createDeviceComparisonChart() {" >> "$INDEX_HTML"
echo "      const ctx = document.getElementById('deviceComparisonChart').getContext('2d');" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      // Calculate average desktop and mobile scores" >> "$INDEX_HTML"
echo "      const desktopScores = { perf: 0, a11y: 0, bp: 0, seo: 0, count: 0 };" >> "$INDEX_HTML"
echo "      const mobileScores = { perf: 0, a11y: 0, bp: 0, seo: 0, count: 0 };" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      performanceData.pages.forEach(page => {" >> "$INDEX_HTML"
echo "        if (page.desktop) {" >> "$INDEX_HTML"
echo "          desktopScores.perf += page.desktop.performance;" >> "$INDEX_HTML"
echo "          desktopScores.a11y += page.desktop.accessibility;" >> "$INDEX_HTML"
echo "          desktopScores.bp += page.desktop.bestPractices;" >> "$INDEX_HTML"
echo "          desktopScores.seo += page.desktop.seo;" >> "$INDEX_HTML"
echo "          desktopScores.count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "        if (page.mobile) {" >> "$INDEX_HTML"
echo "          mobileScores.perf += page.mobile.performance;" >> "$INDEX_HTML"
echo "          mobileScores.a11y += page.mobile.accessibility;" >> "$INDEX_HTML"
echo "          mobileScores.bp += page.mobile.bestPractices;" >> "$INDEX_HTML"
echo "          mobileScores.seo += page.mobile.seo;" >> "$INDEX_HTML"
echo "          mobileScores.count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      const avgDesktopPerf = desktopScores.count > 0 ? Math.round(desktopScores.perf / desktopScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgDesktopA11y = desktopScores.count > 0 ? Math.round(desktopScores.a11y / desktopScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgDesktopBP = desktopScores.count > 0 ? Math.round(desktopScores.bp / desktopScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgDesktopSEO = desktopScores.count > 0 ? Math.round(desktopScores.seo / desktopScores.count) : 0;" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      const avgMobilePerf = mobileScores.count > 0 ? Math.round(mobileScores.perf / mobileScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgMobileA11y = mobileScores.count > 0 ? Math.round(mobileScores.a11y / mobileScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgMobileBP = mobileScores.count > 0 ? Math.round(mobileScores.bp / mobileScores.count) : 0;" >> "$INDEX_HTML"
echo "      const avgMobileSEO = mobileScores.count > 0 ? Math.round(mobileScores.seo / mobileScores.count) : 0;" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      const deviceChart = new Chart(ctx, {" >> "$INDEX_HTML"
echo "        type: 'bar'," >> "$INDEX_HTML"
echo "        data: {" >> "$INDEX_HTML"
echo "          labels: ['Performance', 'Accessibility', 'Best Practices', 'SEO']," >> "$INDEX_HTML"
echo "          datasets: [" >> "$INDEX_HTML"
echo "            {" >> "$INDEX_HTML"
echo "              label: 'Desktop'," >> "$INDEX_HTML"
echo "              data: [avgDesktopPerf, avgDesktopA11y, avgDesktopBP, avgDesktopSEO]," >> "$INDEX_HTML"
echo "              backgroundColor: 'rgba(54, 162, 235, 0.6)'," >> "$INDEX_HTML"
echo "              borderColor: 'rgb(54, 162, 235)'," >> "$INDEX_HTML"
echo "              borderWidth: 1" >> "$INDEX_HTML"
echo "            }," >> "$INDEX_HTML"
echo "            {" >> "$INDEX_HTML"
echo "              label: 'Mobile'," >> "$INDEX_HTML"
echo "              data: [avgMobilePerf, avgMobileA11y, avgMobileBP, avgMobileSEO]," >> "$INDEX_HTML"
echo "              backgroundColor: 'rgba(255, 99, 132, 0.6)'," >> "$INDEX_HTML"
echo "              borderColor: 'rgb(255, 99, 132)'," >> "$INDEX_HTML"
echo "              borderWidth: 1" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          ]" >> "$INDEX_HTML"
echo "        }," >> "$INDEX_HTML"
echo "        options: {" >> "$INDEX_HTML"
echo "          responsive: true," >> "$INDEX_HTML"
echo "          maintainAspectRatio: false," >> "$INDEX_HTML"
echo "          scales: {" >> "$INDEX_HTML"
echo "            y: {" >> "$INDEX_HTML"
echo "              beginAtZero: true," >> "$INDEX_HTML"
echo "              max: 100," >> "$INDEX_HTML"
echo "              title: {" >> "$INDEX_HTML"
echo "                display: true," >> "$INDEX_HTML"
echo "                text: 'Score (%)'" >> "$INDEX_HTML"
echo "              }" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          }," >> "$INDEX_HTML"
echo "          plugins: {" >> "$INDEX_HTML"
echo "            legend: {" >> "$INDEX_HTML"
echo "              position: 'top'" >> "$INDEX_HTML"
echo "            }," >> "$INDEX_HTML"
echo "            title: {" >> "$INDEX_HTML"
echo "              display: false" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

echo "    // Create the page comparison chart" >> "$INDEX_HTML"
echo "    function createPageComparisonChart() {" >> "$INDEX_HTML"
echo "      const ctx = document.getElementById('pageComparisonChart').getContext('2d');" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      // Prepare data for each page" >> "$INDEX_HTML"
echo "      const pageNames = [];" >> "$INDEX_HTML"
echo "      const pagePerformance = [];" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      performanceData.pages.forEach(page => {" >> "$INDEX_HTML"
echo "        pageNames.push(page.name);" >> "$INDEX_HTML"
echo "        // Average desktop and mobile performance if both exist, otherwise use what's available" >> "$INDEX_HTML"
echo "        let score = 0;" >> "$INDEX_HTML"
echo "        let count = 0;" >> "$INDEX_HTML"
echo "        if (page.desktop) {" >> "$INDEX_HTML"
echo "          score += page.desktop.performance;" >> "$INDEX_HTML"
echo "          count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "        if (page.mobile) {" >> "$INDEX_HTML"
echo "          score += page.mobile.performance;" >> "$INDEX_HTML"
echo "          count++;" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "        pagePerformance.push(count > 0 ? Math.round(score / count) : 0);" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"
echo "      " >> "$INDEX_HTML"
echo "      const pageChart = new Chart(ctx, {" >> "$INDEX_HTML"
echo "        type: 'bar'," >> "$INDEX_HTML"
echo "        data: {" >> "$INDEX_HTML"
echo "          labels: pageNames," >> "$INDEX_HTML"
echo "          datasets: [" >> "$INDEX_HTML"
echo "            {" >> "$INDEX_HTML"
echo "              label: 'Performance Score'," >> "$INDEX_HTML"
echo "              data: pagePerformance," >> "$INDEX_HTML"
echo "              backgroundColor: pagePerformance.map(score => {" >> "$INDEX_HTML"
echo "                if (score >= 90) return 'rgba(75, 192, 192, 0.6)';" >> "$INDEX_HTML"
echo "                if (score >= 75) return 'rgba(255, 206, 86, 0.6)';" >> "$INDEX_HTML"
echo "                return 'rgba(255, 99, 132, 0.6)';" >> "$INDEX_HTML"
echo "              })," >> "$INDEX_HTML"
echo "              borderColor: pagePerformance.map(score => {" >> "$INDEX_HTML"
echo "                if (score >= 90) return 'rgb(75, 192, 192)';" >> "$INDEX_HTML"
echo "                if (score >= 75) return 'rgb(255, 206, 86)';" >> "$INDEX_HTML"
echo "                return 'rgb(255, 99, 132)';" >> "$INDEX_HTML"
echo "              })," >> "$INDEX_HTML"
echo "              borderWidth: 1" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          ]" >> "$INDEX_HTML"
echo "        }," >> "$INDEX_HTML"
echo "        options: {" >> "$INDEX_HTML"
echo "          responsive: true," >> "$INDEX_HTML"
echo "          maintainAspectRatio: false," >> "$INDEX_HTML"
echo "          scales: {" >> "$INDEX_HTML"
echo "            y: {" >> "$INDEX_HTML"
echo "              beginAtZero: true," >> "$INDEX_HTML"
echo "              max: 100," >> "$INDEX_HTML"
echo "              title: {" >> "$INDEX_HTML"
echo "                display: true," >> "$INDEX_HTML"
echo "                text: 'Score (%)'" >> "$INDEX_HTML"
echo "              }" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          }," >> "$INDEX_HTML"
echo "          plugins: {" >> "$INDEX_HTML"
echo "            legend: {" >> "$INDEX_HTML"
echo "              display: false" >> "$INDEX_HTML"
echo "            }," >> "$INDEX_HTML"
echo "            title: {" >> "$INDEX_HTML"
echo "              display: false" >> "$INDEX_HTML"
echo "            }" >> "$INDEX_HTML"
echo "          }" >> "$INDEX_HTML"
echo "        }" >> "$INDEX_HTML"
echo "      });" >> "$INDEX_HTML"
echo "    }" >> "$INDEX_HTML"

# Add document load event handler
echo "    // Load data when the page loads" >> "$INDEX_HTML"
echo "    document.addEventListener('DOMContentLoaded', loadReportData);" >> "$INDEX_HTML"
echo "  </script>" >> "$INDEX_HTML"
echo "</body>" >> "$INDEX_HTML"
echo "</html>" >> "$INDEX_HTML"

echo "Dashboard file generated at $INDEX_HTML"