name: "Prepare GitHub Pages"
description: "Prepares files for GitHub Pages deployment"

inputs:
  publish-dir:
    description: "Directory to publish to GitHub Pages"
    required: true
  repository:
    description: "Repository name for README"
    required: true

runs:
  using: "composite"
  steps:
    # Check if download was successful and create a fallback if not
    - name: Check download and create fallback if needed
      shell: bash
      run: |
        echo "Checking contents of ${{ inputs.publish-dir }} directory:"
        ls -la ${{ inputs.publish-dir }} || echo "Directory is empty"

        # Create fallback index.html if it doesn't exist
        if [ ! -f "${{ inputs.publish-dir }}/index.html" ]; then
          echo "Creating fallback index.html file..."
          TEMPLATE_DIR="${{ github.workspace }}/.github/workflows/templates"
          CURRENT_DATE=$(date)

          cat "$TEMPLATE_DIR/minimal-dashboard.template.html" | \
            sed -e "s|\${GENERATION_DATE}|$CURRENT_DATE|g" \
            > "${{ inputs.publish-dir }}/index.html"

          echo "Created fallback index.html"
        fi

        echo "Contents of ${{ inputs.publish-dir }} directory:"
        find ${{ inputs.publish-dir }} -type f | sort || echo "No files found"

    # Make sure we have a proper .nojekyll file BEFORE deploying
    - name: Prepare GitHub Pages files
      shell: bash
      run: |
        # Create .nojekyll file to disable Jekyll processing
        touch ${{ inputs.publish-dir }}/.nojekyll
        echo "Created .nojekyll file"

        # Force index.html to be the default file
        cp ${{ inputs.publish-dir }}/index.html ${{ inputs.publish-dir }}/default.html || echo "No index.html to copy"

        # Create a README that points to index.html
        echo "# Lighthouse Dashboard" > ${{ inputs.publish-dir }}/README.md
        echo "" >> ${{ inputs.publish-dir }}/README.md
        echo "This is the Lighthouse performance dashboard for ${{ inputs.repository }}." >> ${{ inputs.publish-dir }}/README.md
        echo "It's updated automatically by GitHub Actions." >> ${{ inputs.publish-dir }}/README.md
        echo "" >> ${{ inputs.publish-dir }}/README.md
        echo "**[View Dashboard](./index.html)**" >> ${{ inputs.publish-dir }}/README.md
        echo "" >> ${{ inputs.publish-dir }}/README.md
        echo "Last updated: $(date)" >> ${{ inputs.publish-dir }}/README.md

        # Create a simple HTML redirector at the root level
        TEMPLATE_DIR="${{ github.workspace }}/.github/workflows/templates"
        cat "$TEMPLATE_DIR/redirect.template.html" | \
          sed -e "s|\${REDIRECT_URL}|./index.html|g" \
              -e "s|\${REDIRECT_TITLE}|dashboard|g" \
          > "${{ inputs.publish-dir }}/_index.html"

        echo "Files prepared for GitHub Pages:"
        ls -la ${{ inputs.publish-dir }}/
