name: Lighthouse CI

on:
  schedule:
    - cron: "15 2 * * *" # Run every day at 2:15 UTC
    - cron: "15 14 * * *" # Run every day at 14:15 UTC
  # Allow manual trigger through GitHub UI
  workflow_dispatch:
  pull_request:
    branches: [main, master]

# Allow cancellation of previous runs in the same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  lighthouse-desktop:
    name: Lighthouse CI (Desktop)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        page:
          - name: homepage
            url: https://curalife.com/
          - name: product
            url: https://curalife.com/products/curalin
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Run Lighthouse CI (Desktop)
        id: lighthouse-desktop
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: ${{ matrix.page.url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ./lighthouserc.json
          runs: 3
          prettyPrintResults: true
          budgetPath: ./budgets.json
          collect.settings.preset: desktop

      - name: Create PR Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const results = ${{ steps.lighthouse-desktop.outputs.manifest }};
            const links = ${{ steps.lighthouse-desktop.outputs.links }};

            if (!results || !links) return;

            const result = JSON.parse(results)[0];
            const link = JSON.parse(links)[0];

            const comment = [
              `## Lighthouse Results for ${{ matrix.page.name }} (Desktop) 🚀`,
              '',
              '| Category | Score |',
              '| --- | --- |',
              `| Performance | ${result.summary.performance * 100}/100 |`,
              `| Accessibility | ${result.summary.accessibility * 100}/100 |`,
              `| Best Practices | ${result.summary['best-practices'] * 100}/100 |`,
              `| SEO | ${result.summary.seo * 100}/100 |`,
              '',
              `[View Detailed Report](${link.url})`
            ].join('\n');

            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment
            });

  lighthouse-mobile:
    name: Lighthouse CI (Mobile)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        page:
          - name: homepage
            url: https://curalife.com/
          - name: product
            url: https://curalife.com/products/curalin
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Run Lighthouse CI (Mobile)
        id: lighthouse-mobile
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: ${{ matrix.page.url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ./lighthouserc.json
          runs: 3
          prettyPrintResults: true
          budgetPath: ./budgets.json
          collect.settings.preset: mobile

      - name: Create PR Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const results = ${{ steps.lighthouse-mobile.outputs.manifest }};
            const links = ${{ steps.lighthouse-mobile.outputs.links }};

            if (!results || !links) return;

            const result = JSON.parse(results)[0];
            const link = JSON.parse(links)[0];

            const comment = [
              `## Lighthouse Results for ${{ matrix.page.name }} (Mobile) 📱`,
              '',
              '| Category | Score |',
              '| --- | --- |',
              `| Performance | ${result.summary.performance * 100}/100 |`,
              `| Accessibility | ${result.summary.accessibility * 100}/100 |`,
              `| Best Practices | ${result.summary['best-practices'] * 100}/100 |`,
              `| SEO | ${result.summary.seo * 100}/100 |`,
              '',
              `[View Detailed Report](${link.url})`
            ].join('\n');

            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment
            });

  # Compare results between main branch and PR
  compare-lighthouse-results:
    name: Compare Lighthouse Results
    needs: [lighthouse-desktop, lighthouse-mobile]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Compare against main branch
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://curalife.com/
            https://curalife.com/products/curalin
          serverBaseUrl: ${{ secrets.LHCI_SERVER_BASE_URL || '' }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN || '' }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 1
          configPath: ./lighthouserc.json
          compareWithBaseBranch: true

  create-dashboard:
    name: Create Lighthouse Dashboard
    needs: [lighthouse-desktop, lighthouse-mobile]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: lighthouse-artifacts

      - name: Generate Dashboard
        run: |
          # Install required packages
          npm install -g @lhci/utils

          # Create a more structured dashboard
          mkdir -p performance-reports

          cat << EOF > performance-reports/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Lighthouse Dashboard - Curalife</title>
            <style>
              body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.5; max-width: 1200px; margin: 0 auto; padding: 20px; }
              h1, h2 { color: #333; }
              .report-card { border: 1px solid #eee; padding: 15px; margin-bottom: 15px; border-radius: 5px; }
              .report-card h3 { margin-top: 0; }
              .scores { display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 15px; }
              .score { padding: 8px 15px; border-radius: 20px; color: white; font-weight: bold; }
              .perf { background: #0c6; }
              .a11y { background: #7c5; }
              .bp { background: #06c; }
              .seo { background: #c06; }
              a.report-link { display: inline-block; margin-top: 10px; text-decoration: none; padding: 8px 15px; background: #333; color: white; border-radius: 4px; }
              a.report-link:hover { background: #555; }
              .timestamp { color: #666; font-size: 0.9em; margin-bottom: 30px; }
            </style>
          </head>
          <body>
            <h1>Lighthouse Performance Dashboard</h1>
            <p class="timestamp">Generated on $(date)</p>

            <h2>Latest Reports</h2>
            <div id="reports"></div>

            <script>
              // Simple script to organize report links
              const reportsContainer = document.getElementById('reports');

              // We'll populate this with the found reports
              const reports = [];
            </script>
          </body>
          </html>
          EOF

          # Find and process report files
          find lighthouse-artifacts -name "*.report.html" | while read report; do
            cp "$report" performance-reports/
            filename=$(basename "$report")

            # Extract page and device from filename pattern
            if [[ "$filename" == *"mobile"* ]]; then
              device="Mobile"
            else
              device="Desktop"
            fi

            if [[ "$filename" == *"homepage"* ]]; then
              page="Homepage"
            elif [[ "$filename" == *"product"* ]]; then
              page="Product Page"
            else
              page="Unknown Page"
            fi

            # Add to the reports list in the HTML
            echo "<script>" >> performance-reports/index.html
            echo "reports.push({" >> performance-reports/index.html
            echo "  page: '$page'," >> performance-reports/index.html
            echo "  device: '$device'," >> performance-reports/index.html
            echo "  filename: '$filename'" >> performance-reports/index.html
            echo "});" >> performance-reports/index.html
            echo "</script>" >> performance-reports/index.html
          done

          # Add the rendering script
          cat << EOF >> performance-reports/index.html
          <script>
            // Sort and render the reports
            reports.sort((a, b) => {
              if (a.page === b.page) return a.device.localeCompare(b.device);
              return a.page.localeCompare(b.page);
            });

            reports.forEach(report => {
              const card = document.createElement('div');
              card.className = 'report-card';

              card.innerHTML = \`
                <h3>\${report.page} (\${report.device})</h3>
                <a class="report-link" href="./\${report.filename}" target="_blank">View Full Report</a>
              \`;

              reportsContainer.appendChild(card);
            });

            if (reports.length === 0) {
              reportsContainer.innerHTML = '<p>No reports available yet.</p>';
            }
          </script>
          EOF

      - name: Upload Dashboard
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-dashboard
          path: performance-reports
          retention-days: 30

  # Deploy to GitHub Pages if on main/master branch
  deploy-pages:
    name: Deploy to GitHub Pages
    needs: create-dashboard
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Download Dashboard
        uses: actions/download-artifact@v4
        with:
          name: lighthouse-dashboard
          path: ./

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Update Lighthouse dashboard [skip ci]" || echo "No changes to commit"
          git push origin gh-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
